.\"
.\"  Copyright (c) 2015-2017  Savoir-faire Linux, Inc.
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, version 3.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.
.TH "CQFD" "1" "2017-01-17" "C.Q.F.D." "C.Q.F.D. Manual"
.
.SH NAME
cqfdrc - project information config file
.
.SH DESCRIPTION
The
.B .cqfdrc(5)
file at the root of your project contains the information required to support
project tooling.
.I samples/dot-cqfdrc
is an example.
.
.P
The
.B project
section
.
.P
org: a short, lowercase name for the project’s parent organization.
name: a short, lowercase name for the project.

Generated Docker images for your project will be named
.I $org_$name
;
.
.P
The
.B build
section
.
.P
.IP command
the command (or list of commands) to be executed when cqfd is invoked. This
string will be passed as an argument to a classical bash -c "commands", within
the build container, to generate the build artefacts.
.
.IP files
an optional space-separated list of files generated by the build process that we
want to include inside a standard release archive.
.
.IP archive
the optional name of the release archive generated by cqfd. You can include
environment variable names, as well as the following template marks:
    %Gh - git short hash of last commit
    %GH - git long hash of last commit
    %D3 - RFC3339 date (YYYY-MM-DD)
    %Cf - current cqfd flavor name (if any)
    %Po - value of the project.org configuration key
    %Pn - value of the project.name configuration key
    %% - a litteral '%' sign
.
.P
By default,
.B cqfd(1)
will generate a release tarball named
.I org-name.tar.xz
, where `org' and `name' come from the project's configuration keys.
.
.IP flavors
the list of build flavors (see below). Each flavor has its own command just like build.command.
.
.SH EXAMPLES
.P
Here is a sample
.B .cqfdrc(5)
file:
.
.P
.in +4n
.nf
[project]
org='fooinc'
name='buildroot'

[build]
command='make foobar_defconfig && make && asciidoc README.FOOINC'
files='README.FOOINC output/images/sdcard.img'
archive='cqfd-%Gh.tar.xz'
.fi
.in
.
.SH BUGS
Report bugs at
.RB < https://github.com/savoirfairelinux/cqfd/issues >
.
.SH AUTHOR
Originally written by Mathieu Audat
.RB < mathieu.audat@savoirfairelinux.com >
.
.SH COPYRIGHT
Copyright (C) 2015-2017 Savoir-faire Linux, Inc.
.
.P
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.
.
.SH SEE ALSO
.BR cqfd(1)
.
.SH COLOPHON
This page is part of
.B C.Q.F.D.
project.
.
.P
.B C.Q.F.D.
stands for `Ce qu'il fallait Dockeriser', french for `what needed to be
dockerized'.
