= cqfd6(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@gmail.com.com
:lang: en
:man manual: C.Q.F.D. S.I.X. Manual
:man source: C.Q.F.D. S.I.X. Project 6

== NAME

cqfd - a tool to wrap commands in controlled Docker containers using docker.

== SYNOPSIS

*cqfd* [OPTIONS] --init|--deinit

*cqfd* [OPTIONS] --ls|--gc

*cqfd* [OPTIONS] --exec COMMAND [ARGUMENTS]

*cqfd* [OPTIONS] --flavors

*cqfd* [OPTIONS] --run [COMMAND_STRING]

*cqfd* [OPTIONS] --run -c ARGUMENT_STRING

*cqfd* [OPTIONS] --shell [SHELL_ARGUMENTS]

*cqfd* [OPTIONS] [--] [PROGRAM] [ARGUMENTS]

== DESCRIPTION

*cqfd(1)* provides a quick and convenient way to run commands in the current
directory, but within a Docker container defined in a per-project config file.

This becomes useful when building an application designed for another Linux
system, e.g. building an old embedded firmware that only works in an older
Linux distribution.

== COMMANDS

*--init*::
	Initialize project build container.

*--deinit*::
	Deinitialize project build container.

*--ls::
	List build containers.

*--gc*::
	Cleanup unused build containers.

*--exec PROGRAM [ARGUMENTS]*::
	Run command inside build container.

*--flavors*::
	List flavors from config file to stdout.

*--run [COMMAND_STRING]*::
	Run command string inside build container.

*--shell [SH_ARGUMENTS]*::
	Run shell command inside build container.

By default, the _--run_ command is assumed, with the default command string
configured in your _.cqfdrc_ (see build.command).

Command options for --run:

*-c ARGUMENT_STRING*::
	Append argument string to the default command string.

== OPTIONS

*--reinit*:
	Reinitialize build container.

*--release*::
	Release software.

*--platform TARGET*::
	Set target platform.

*-f* or *--cqfdrc-file FILE*::
	Use file as config file (default _.cqfdrc_).

*-d* or *--cqfd-directory DIR*::
	Use directory as cqfd directory (default _.cqfd_).

*-w* or *--working-directory DIR*::
	Use directory as working directory (default parent of _.cqfd_).

*-C* or *--directory DIR*::
	Change to the specified working directory.

*-b* or *--build FLAVOR*::
	Target a specific build flavor.

*-q* or *--quiet*::
	Turn on quiet mode.

*-v* or *--version*::
	Show version.

*-h* or *--help*::
	Show this help text.

== ENVIRONMENT VARIABLES

*CQFD_WORKDIR*::
	Directory used as working directory (default parent of _.cqfd_).

*CQFD_DIR*::
	Directory used as cqfd directory (default _.cqfd_).

*CQFDRC_FILE*::
	File used as config file (default _.cqfdrc_).

*CQFD_DOCKER*::
	Program used to invoke _docker_ client.

*CQFD_EXTRA_RUN_ARGS*::
	A space-separated list of additional docker-run options to be append to
	the starting build container. Format is the same as (and passed to)
	docker-run’s options. See 'docker run --help'.

*CQFD_EXTRA_BUILD_ARGS*::
	A space-separated list of additional docker-build options to be append
	to the building image. Format is the same as (and passed to)
	docker-build’s options. See 'docker build --help'.

*CQFD_EXTRA_PULL_ARGS*::
	A space-separated list of additional docker-pull options to be append
	to the pullind image. Format is the same as (and passed to)
	docker-pull’s options. See 'docker pull --help'.

*CQFD_EXTRA_RMI_ARGS*::
	A space-separated list of additional docker-rmi options to be append
	to the removed image. Format is the same as (and passed to)
	docker-rmi’s options. See 'docker rmi --help'.

*CQFD_NO_SSH_CONFIG*::
	Set to _true_ to disable forwarding the global _/etc/ssh_
	configurations to the build container. This may be required if the host's
	_ssh_ configuration is not compatible with the _ssh_ version within the
	build container.

*CQFD_NO_USER_SSH_CONFIG*::
	Set to _true_ to disable forwarding the user's _~/.ssh_ configuration
	to the build container.

*CQFD_NO_USER_GIT_CONFIG*::
	Set to _true_ to disable forwarding the user's _~/.gitconfig_
	configuration to the build container.

*CQFD_NO_SSH_AUTH_SOCK*::
	Set to _true_ to disable forwarding the SSH authentication socket to
	the build container.

*CQFD_BIND_DOCKER_SOCK*::
	Set to _true_ to enable forwarding the docker socket to the build
	container.

*CQFD_DOCKER_GID*::
	The gid of the docker group in host to map to the cqfd group in the
	build container.

*CQFD_SHELL*::
	The shell to be launched, by default _/bin/sh_.

*CQFD_RUN_WITH_SUDO*::
	Set to _true_ to run _$CQFD_DOCKER_ with _sudo_.

== FILES

*.cqfdrc*::
	Project information config file (See *cqfdrc(5)*).

*.cqfd*::
	Project data directory.

*.cqfd/docker/Dockerfile*::
	Default docker config file (See *Dockerfile(5)*).

== PATCHES

Submit patches at *https://github.com/gportay/cqfd6/pulls*

== BUGS

Report bugs at *https://github.com/gportay/cqfd6/issues*

== COPYRIGHT

Copyright (C) 2017,2025 Gaël PORTAY

Copyright (C) 2015-2025 Savoir-faire Linux, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

== TRIVIA

CQFD stands for "ce qu'il fallait Dockeriser", French for "what needed to be
Dockerized".

SIX stands for *Sudo Interface eXperimentation*.

== SEE ALSO

*docker-build(1)*, *docker-run(1)*, *Dockerfile(5)*, *cqfdrc(5)*
