= cqfd(1)
:doctype: manpage
:author: Gaël PORTAY
:email: gael.portay@savoirfairelinux.com
:lang: en
:man manual: C.Q.F.D. Manual
:man source: C.Q.F.D. Project

== NAME

cqfd - a tool to wrap commands in controlled Docker containers

== SYNOPSIS

*cqfd* [OPTIONS] [COMMAND] [ARGUMENTS]

== DESCRIPTION

*cqfd(1)* provides a quick and convenient way to run commands in the current
directory, but within a Docker container defined in a per-project config file.

This becomes useful when building an application designed for another Linux
system, e.g. building an old embedded firmware that only works in an older
Linux distribution.

== COMMANDS

**init**::
    Initialize project build container.

**destroy**::
    Destroy project build container.

*run*::
    Run argument(s) inside build container

**exec cmd [args]**::
    Run argument(s) inside build container.

**flavors**::
    List flavors from config file to stdout.

**run [cmdstring]**::
    Run argument(s) inside build container.

**release [cmdstring]*::
    Run argument(s) and release software.

**shell [shargs]**::
    Run shell command inside build container.

**help**::
    Show this help text.

== OPTIONS

**-f <file>**::
    Use file as config file (default .cqfdrc).

**-d <directory>**::
    Use directory as cqfd directory (default .cqfd).

**-C <directory>**::
    Use the specified working directory.

**-b <flavor_name>**::
    Target a specific build flavor.

**-q**::
    Turn on quiet mode.

**-v** or **--version**
    Show version.

**--verbose**::
    Increase the script's verbosity.

**-h** or **--help**
    Show this help text.

## EXAMPLES

*Regular builds*

To build your project from the configured build environment with the default
build command as configured in *.cqfdrc(5)*, use:

    $ cqfd

Alternatively, you may want to specify a single custom command to be executed
from inside the build container.

    $ cqfd exec make clean

Or custom commands composed with shell grammar:

    $ cqfd shell -c "make linux-dirclean && make foobar-dirclean"

Or run a shell script with arguments:

    $ cqfd shell ./build.sh debug

When *cqfd(1)* is running, the current directory is mounted by Docker as a
volume. As a result, all the build artefacts generated inside the container are
still accessible in this directory after the container has been stopped and
removed.

*Release*

The _release_ command behaves exactly like _run_, but creates a release tarball
for your project additionally. The release files (as specified in your
*.cqfdrc(5)*) will be included inside the release archive.

    $ cqfd release

The resulting release file is then called according to the archive template,
which defaults to _%Po-%Pn.tar.xz_.

*Flavors*

Flavors are used to create alternate build scenarios. For example, to
use another container or another build command.

You may also want to build a specific build _flavor_, for a regular build or a
release. To do so use the _-b_ option, for example:

    $ cqfd -b debug run

When building with a _flavor_ as when building a regular project, the run
option can be omitted.

*Other command-line options*

In some conditions you may want to use an alternate config file with *cqfd(1)*.
This is what the _-f_ option is for:

    $ cqfd -f .cqfdrc.test

== FILES

*.cqfdrc*::
    Project information config file (See *cqfdrc(5)*).

== ENVIRONMENT

The following environment variables are supported by cqfd to provide the user
with extra flexibility during his day-to-day development tasks:

**CQFD_EXTRA_RUN_ARGS**::
    A space-separated list of additional *docker-run(1)* options to be append
    to the starting container. Format is the same as (and passed to)
    *docker-run(1)*'s options.

**CQFD_EXTRA_BUILD_ARGS**::
    A space-separated list of additional *docker-build(1)* options to be append
    to the building image. Format is the same as (and passed to)
    *docker-build(1)*’s options.

**CQFD_NO_SSH_CONFIG**::
    Set to _true_ to disable forwarding the global _/etc/ssh_ configurations to
    the container. This may be required if the host's *ssh(1)* configuration is
    not compatible with the *ssh(1)* version within the container.

**CQFD_NO_USER_SSH_CONFIG**::
    Set to _true_ to disable forwarding the user's _~/.ssh_ configuration to
    the container.

**CQFD_NO_USER_GIT_CONFIG**::
    Set to _true_ to disable forwarding the user's _~/.gitconfig_ configuration
    to the container.

**CQFD_SHELL**::
    The shell to be launched, by default _/bin/sh_.

== BUGS

Report bugs at *http://github.com/savoirfairelinux/cqfd/issues*

== AUTHOR

Originally written by Mathieu Audat *mathieu.audat@savoirfairelinux.com*

== COPYRIGHT

Copyright (C) 2015-2025 Savoir-faire Linux, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3.

== SEE ALSO

*cqfdrc(5)*, *docker(1)*, *docker-run(1)*, *docker-build(1)*, *Dockerfile(5)*

== COLOPHON

This page is part of *C.Q.F.D.* project.

*C.Q.F.D.* stands for `Ce qu'il fallait Dockeriser', french for `what needed
to be dockerized'.
