#!/usr/bin/env bash
#
# cqfd - a tool to wrap commands in controlled Docker containers
#
# Copyright (C) 2024-2026 Gaël PORTAY
#               2015-2025 Savoir-faire Linux, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [[ "$1" == "docker-cli-plugin-metadata" ]]; then
	cat <<EOF
{
	"SchemaVersion":"0.1.0",
	"Vendor":"Gaël PORTAY",
	"Version":"$(cqfd6 --version)",
	"ShortDescription":"A tool to wrap commands in controlled Docker containers.",
	"URL":"https://github.com/gportay/cqfd6"
}
EOF
	exit 0
fi

if [[ "$1" == "__complete" ]]; then
	# Called as docker-cqfd __complete cqfd
	shift
	shift

	source /usr/share/bash-completion/bash_completion
	source /usr/share/bash-completion/completions/cqfd6

	COMP_LINE="cqfd6 $*"
	COMP_WORDS=(cqfd6 "$@")
	COMP_CWORD="$#"
	COMP_POINT="${#COMP_LINE}"
	_cqfd6
	printf "%s\n" "${COMPREPLY[@]}"
	exit 0
fi

if [[ "$1" == "help" ]]; then
	cat <<EOF
Usage:  docker cqfd [--] [PROGRAM] [ARGUMENTS]

A tool to wrap commands in controlled Docker containers.

Options:
      --reinit                           Reinitialize build container.
      --release                          Release software.
      --platform string                  Set target platform.
  -f, --cqfdrc-file string               Use file as config file (default .cqfdrc).
  -d, --cqfd-directory string            Use directory as cqfd directory (default .cqfd).
  -w, --working-directory string         Use directory as working directory (default parent of .cqfd).
  -C, --directory string                 Use the specified working directory.
  -b, --build string                     Target a specific build flavor.
  -q, --quiet                            Turn on quiet mode.
  -v, --version                          Show version.
      --compatibility                    Show compatibility level.
  -D, --verbose                          Increase the script's verbosity.
  -h, --help                             Show this help text.

Commands:
  --init                                 Initialize project build container.
  --deinit                               Deinitialize project build container.
  --ls                                   List build containers.
  --gc                                   Cleanup unused build containers.
  --exec cmd [list]                      Run argument(s) inside build container.
  --flavors                              List flavors from config file to stdout.
  --run [list]                           Run argument(s) inside build container.
  --shell [list]                         Run shell command inside build container.

  By default, the 'run' command is assumed, with the default command string configured in your .cqfdrc (see build.command).

Command options for --run:
  -c string                              Append argument string to the default command string.
EOF
	exit
fi

# Called as docker-cqfd cqfd
shift
exec cqfd "$@"
