#!/usr/bin/env bash
#
# validate the behavior with skelton bring up

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

################################################################################
# running 'cqfd init' without a proper config directory should fail
################################################################################
jtest_prepare "cqfd init complains without an .cqfd directory"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# initially, for setup, insert a proper testing .cqfd directory
################################################################################
mv cqfd .cqfd

################################################################################
# running 'cqfd ls' without a proper config file should fail
################################################################################
jtest_prepare "cqfd ls complains without an .cqfdrc file"
if ! cqfd ls; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# running 'cqfd gc' without a proper config file should fail
################################################################################
jtest_prepare "cqfd gc complains without an .cqfdrc file"
if ! cqfd gc; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# running 'cqfd init' should fail, as there's no proper config file
################################################################################
jtest_prepare "create a test skeleton in temporary directory"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# running 'cqfd init' should fail, as there's an empty config file
################################################################################
jtest_prepare "cqfd init complains with an empty .cqfdrc file"
touch "$TDIR/.cqfdrc"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# running 'cqfd init' should fail, as there's an incomplete config file
################################################################################
jtest_prepare "cqfd init complains with an incomplete .cqfdrc file"
echo '[project]' >"$TDIR/.cqfdrc"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# finally, for setup, insert a proper testing .cqfdrc file
################################################################################
cat "$TDIR/cqfdrc-test" >"$TDIR/.cqfdrc"
