#!/usr/bin/env bash
#
# validate the behavior with skelton bring up

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd init without an .cqfd directory should fail"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

mv cqfd .cqfd

jtest_prepare "run cqfd ls without a .cqfdrc file should fail"
if ! cqfd ls; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd gc without a .cqfdrc file should fail"
if ! cqfd gc; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init without a .cqfdrc file should fail"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with an empty .cqfdrc file should fail"
touch .cqfdrc
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with an incomplete .cqfdrc file should fail"
echo '[project]' >.cqfdrc
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

cp cqfdrc-test .cqfdrc
