#!/usr/bin/env bash
#
# validate the behavior of init command

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd init with a .cqfdrc file should pass"
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

jtest_prepare "run cqfd init with a nonexistent Dockerfile should fail"
sed -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc.orig >.cqfdrc
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with another Dockerfile should pass"
sed -e "s/thisshouldfail/centos/" -i .cqfdrc
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc

# backup Dockerfile
mv .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "run cqfd init with same uid/gid dummy user should pass"
cat .cqfd/docker/Dockerfile.orig <<EOF >>.cqfd/docker/Dockerfile
RUN groupadd -og "${GROUPS[0]}" -f dummy && \
    useradd -s /bin/bash -ou "$UID" -g "${GROUPS[0]}" dummy
EOF
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with --quiet should remain quiet"
if ! cqfd -q init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
	jtest_result fail
else
	jtest_result pass
fi

# restore Dockerfile
mv .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
