#!/usr/bin/env bash
#
# validate the behavior of init command

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# create a special test context
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "run cqfd init with a proper .cqfdrc file should pass"
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with a nonexisting Dockerfile should fail"
cp -f .cqfdrc .cqfdrc.orig
sed -i -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with an other Dockerfile should pass"
sed -i -e "s/thisshouldfail/centos/" .cqfdrc
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi
# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc

jtest_prepare "run cqfd init with same uid/gid dummy user should pass"
cat <<EOF >>.cqfd/docker/Dockerfile
RUN groupadd -og "${GROUPS[0]}" -f dummy && \
    useradd -s /bin/bash -ou "$UID" -g "${GROUPS[0]}" dummy
EOF
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with --quiet should remain quiet"
if ! cqfd -q init | grep -E "^(sha256:)?[a-f0-9]{64}$"; then
	jtest_result fail
else
	jtest_result pass
fi

# restore initial Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
