#!/usr/bin/env bash
#
# validate the .cqfdrc syntax

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig

echo -n "" >.cqfdrc

jtest_prepare "cqfdrc fails if no project section"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing project section!$"; \
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

echo "[project]" >>.cqfdrc

jtest_prepare "cqfdrc fails if no name property set in project section"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing project.org or project.name properties!$"; \
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

echo "name=test" >>.cqfdrc

jtest_prepare "cqfdrc fails if no org property set in project section"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing project.org or project.name properties!$"; \
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

echo "org=cqfd" >>.cqfdrc

jtest_prepare "cqfdrc fails if no build section"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing build section!$"; \
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

echo "[build]" >>.cqfdrc

jtest_prepare "cqfdrc fails if no command property set in build section"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing build.command property!$";
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfdrc fails if no command property set in build section even if using run -c"
if cqfd run -c true 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing build.command property!$";
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

echo "command=true" >>.cqfdrc

jtest_prepare "cqfdrc succeeds if project and build sections are set correctly"
if cqfd init && cqfd run true; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfdrc succeeds if command property set in build section using run -c"
if cqfd run -c true 2>&1 | grep "^cqfd: warning: .cqfdrc: Missing or empty build.command property!$"; \
   test "${PIPESTATUS[0]}" -eq 0 -a "${PIPESTATUS[1]}" -ne 0; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
echo "foo	=bar" >>.cqfdrc

jtest_prepare "cqfdrc with tabulation before should pass"
if cqfd run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
echo "foo=	bar" >>.cqfdrc

jtest_prepare "cqfdrc with tabulation after should pass"
if cqfd run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
echo "foo =bar" >>.cqfdrc

jtest_prepare "cqfdrc with space before should pass"
if cqfd run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
echo "foo= bar" >>.cqfdrc

jtest_prepare "cqfdrc with space after should pass"
if cqfd run true; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='true; echo \"; works!\"'," .cqfdrc

jtest_prepare "cqfdrc does not strip semicolons in command"
if cqfd init && cqfd | grep "^; works!$" ; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='true; echo \"# works!\"'," .cqfdrc

jtest_prepare "cqfdrc does not strip hash in command"
if cqfd init && cqfd | grep "^# works!$" ; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command=\"echo \\\\\\
	foo=bar \\\\\\
	baz=quux\"," .cqfdrc

jtest_prepare "cqfdrc with multiline should pass"
if cqfd | grep "^foo=bar baz=quux$"; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
sed -i -e "/\[project\]/,/^$/s,^,; ," .cqfdrc

jtest_prepare "cqfdrc with ;-commented project section should fail"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing project section!$"; \
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
sed -i -e "/\[build\]/,/^$/s,^,# ," .cqfdrc

jtest_prepare "cqfdrc with #-commented build section should fail"
if cqfd 2>&1 | grep "^cqfd: fatal: .cqfdrc: Missing build section!$"; \
   test "${PIPESTATUS[0]}" -eq 1 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

cp -f .cqfdrc.orig .cqfdrc
sed -i -e "/[build]/,/^$/s,^command=.*$,command=\"make foo\"," .cqfdrc
echo "include /dev/null" >>.cqfdrc
rm -f foo

jtest_prepare "cqfdrc with include empty file should pass"
if cqfd && test -e foo; then
	jtest_result pass
else
	jtest_result fail
fi

cat <<EOF >bar.inc
[build]
command="make bar"
EOF
echo "include bar.inc" >>.cqfdrc
rm -f bar

jtest_prepare "cqfdrc with include file should pass"
if cqfd && test -e bar; then
	jtest_result pass
else
	jtest_result fail
fi

echo "include bar.inc" >>.cqfdrc
rm -f bar

jtest_prepare "cqfdrc with duplicate include file should pass"
if cqfd && test -e bar; then
	jtest_result pass
else
	jtest_result fail
fi

echo "include bar.inc" >>bar.inc

jtest_prepare "cqfdrc with recursive include file should fail"
if ! cqfd; then
	jtest_result pass
else
	jtest_result fail
fi

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
