#!/usr/bin/env bash
#
# validate the behavior of help command

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd help should exit success"
if cqfd help >usage; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd help should produce an usage output"
# Those words shall be present in the output
for word in Usage Options Commands; do
	if ! grep -q "^$word:" usage; then
		jtest_log error "cannot find $word in help message"
		rm -f usage
		missing=1
		break
	fi
done
if [ "$missing" != "1" ]; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
rm -f usage
