#!/usr/bin/env bash
#
# validate the behavior with erroneous usages

set -e

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.cqfd/cqfd"

################################################################################
# Running cqfd with an empty argument shall fail
################################################################################
jtest_prepare "run an empty cqfd command-line shall fail"
if ! "$cqfd" ""; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Running cqfd with an unknown argument shall fail
################################################################################
jtest_prepare "run a bad cqfd command-line shall fail"
if ! "$cqfd" invalid_arg_should_fail; then
	jtest_result pass
else
	jtest_result fail
fi
