#!/usr/bin/env bash
#
# validate the behavior of help command

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"

################################################################################
# 'cqfd help' shall be an accepted command
################################################################################
jtest_prepare "cqfd help shall exit normally"
if "$cqfd" help >"$TDIR/usage"; then
	jtest_result pass
else
	jtest_result fail
	rm -f "$TDIR/usage"
fi

################################################################################
# 'cqfd help' shall produce a useful help message
################################################################################
jtest_prepare "cqfd help shall produce an help message"
# Those words shall be present in the output
for word in Usage Options Commands; do
	if ! grep -q "^$word:" "$TDIR/usage"; then
		jtest_log error "cannot find $word in help message"
		rm -f "$TDIR/usage"
		missing=1
		break
	fi
done
if [ "$missing" != "1" ]; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
rm -f "$TDIR/usage"
