#!/usr/bin/env bash
#
# validate the behavior of version command

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd version' shall be an accepted command
################################################################################
jtest_prepare "run cqfd version should exit success"
# shellcheck disable=SC2094
if cqfd version >version; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd version' shall produce a version message
################################################################################
jtest_prepare "run cqfd version should produce a version output"
if grep -qE "^[0-9.]+(-[a-z]+)?\$" version; then
	jtest_result pass
else
	jtest_log error "not a version message"
	jtest_result fail
fi

# cleanup
rm -f version
