#!/usr/bin/env bash
#
# validate the behavior with erroneous usages

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd with an empty argument should fail"
if ! CQFD_COMPAT=5 cqfd ""; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with an unknown command should fail"
if ! CQFD_COMPAT=5 cqfd invalid_arg_should_fail; then
	jtest_result pass
else
	jtest_result fail
fi
