#!/usr/bin/env bash
#
# validate the behavior of project.build_context

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd init without using build_context should not use context directory"
if cqfd init && \
   cqfd run "! test -e /tmp/Cqfdfile-build_context"; then
	jtest_result pass
else
	jtest_result fail
fi

# create a special test context
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.build_context .cqfd/docker/Dockerfile
cp -f Cqfdfile-build_context Cqfdfile

jtest_prepare "run cqfd init using build_context should use the context directory"
if cqfd init && \
   cqfd run "test -e /tmp/Cqfdfile-build_context"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore initial Cqfdfile and Dockerfile
cp -f Cqfdfile-test Cqfdfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
