#!/usr/bin/env bash
#
# validate the behavior of project.build_context

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

jtest_prepare "run cqfd init without using build_context should not use context directory"
cp .cqfdrc.orig .cqfdrc
sed -e "/\[build\]/,/^$/s,^command=.*$,command='! test -e /tmp/cqfdrc-build_context'," -i .cqfdrc
if cqfd init && cqfd; then
	jtest_result pass
else
	jtest_result fail
fi

# backup Dockerfile
mv .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "run cqfd init using build_context should use the context directory"
cp .cqfd/docker/Dockerfile.build_context .cqfd/docker/Dockerfile
cp cqfdrc-build_context .cqfdrc
sed -e "/\[build\]/,/^$/s,^command=.*$,command='test -e /tmp/cqfdrc-build_context'," -i .cqfdrc
if cqfd init && cqfd; then
	jtest_result pass
else
	jtest_result fail
fi

# restore .cqfdrc and Dockerfile
mv .cqfdrc.orig .cqfdrc
mv .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
