#!/usr/bin/env bash
#
# validate the behavior of run command su and sudo backends

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "run cqfd run with ancient su should run su -c"
echo "FROM ubuntu:16.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose run true \
		| awk -v rc=1 '/Using "su" to execute command/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with recent su should run su --session-command"
echo "FROM ubuntu:24.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose run true \
		| awk -v rc=1 '/Using "su" to execute session command/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with sudo should run sudo"
echo "ENV DEBIAN_FRONTEND=noninteractive" >>.cqfd/docker/Dockerfile
echo "RUN apt-get update && apt-get install -y --no-install-recommends sudo" >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose run true \
		| awk -v rc=1 '/Using "sudo" to execute command/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# restore initial Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
