#!/usr/bin/env bash
#
# validate the behavior of run with docker extra run arguments

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup initial .cqfdrc
cp .cqfdrc .cqfdrc.orig
sed -e "/\[build\]/,/^$/s,^command=.*$,command='echo \"\$FOO \$BAR\"'," -i .cqfdrc

jtest_prepare "run cqfd without --env in CQFD_EXTRA_RUN_ARGS and docker_run_args should fail"
if cqfd | grep "^ $"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with --env in CQFD_EXTRA_RUN_ARGS should set environment variables"
if CQFD_EXTRA_RUN_ARGS="--env FOO=foo --env BAR=bar" cqfd | grep "^foo bar$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with --env containing whitespaces in CQFD_EXTRA_RUN_ARGS should set environment variables and preserve whitespaces"
if CQFD_EXTRA_RUN_ARGS="--env FOO=foo\ foobar --env BAR=bar" cqfd | grep "^foo foobar bar$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with --env in docker_run_args should set environment variables"
sed '/\[build\]/adocker_run_args="--env FOO=foo --env BAR=bar"' -i .cqfdrc
if cqfd | grep "^foo bar$"; then
	jtest_result pass
else
	jtest_result fail
fi
sed '/^docker_run_args=/d' -i .cqfdrc

jtest_prepare "run cqfd with --env containing whitespaces in docker_run_args should set environment variables and preserve whitespaces"
sed '/\[build\]/adocker_run_args="--env FOO=foo\\ foobar --env BAR=bar"' -i .cqfdrc
if cqfd | grep "^foo foobar bar$"; then
	jtest_result pass
else
	jtest_result fail
fi
sed '/^docker_run_args=/d' -i .cqfdrc

# restore initial .cqfdrc
mv .cqfdrc.orig .cqfdrc
