#!/usr/bin/env bash
#
# validate the behavior of cqfd with build flavors

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

sed -e "/\[foo\]/,/^$/s,^command=.*$,command='grep ^NAME /etc/os-release'," .cqfdrc.orig >.cqfdrc
sed -e "s/\[foo\]/[foo]\ndistro='centos'/" -i .cqfdrc

jtest_prepare "run cqfd with build flavor should pass"
if cqfd -b foo; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with build flavor should pass"
if cqfd -b foo | grep "^NAME=\"CentOS Linux\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfdwith nonexistent build flavor should fail"
if ! cqfd -b foobar; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with nonexistent build flavor should fail"
if ! cqfd -b foobar; then
	jtest_result pass
else
	jtest_result fail
fi

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
