#!/usr/bin/env bash
#
# validate the behavior of run command with extra arguments

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
test_file="file.$RANDOM"

cd "$TDIR/" || exit 1

# First pass: the command is a single argument
# Data set shall produce $test_file:

jtest_prepare "run cqfd run with argument should run command string"

# shellcheck disable=SC2181
if cqfd run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

# Second pass: the command is the rest of the arguments
# Data set shall produce $test_file:

jtest_prepare "run cqfd run with arguments should run as a command string"

# shellcheck disable=SC2181
if cqfd run touch "$test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

jtest_prepare "run cqfd run with arguments cannot preserve arguments"
# shellcheck disable=SC2016
if cqfd run /bin/sh -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "^0=sh,\*=,#=0$"; \
   test "${PIPESTATUS[0]}" -eq 2; then
	jtest_result pass
else
	jtest_result fail
fi
