#!/usr/bin/env bash
#
# validate the behavior of run with PATH

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

mv -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
mv -f .cqfdrc .cqfdrc.orig

# Use a custom Dockerfile with a busybox version of su.
jtest_prepare "cqfd run with busybox su -c sets path"
sed '/\[build\]/apath="/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin"' .cqfdrc.orig >.cqfdrc
cat <<EOF >.cqfd/docker/Dockerfile
FROM alpine:3.20
RUN apk update && apk upgrade
RUN apk add shadow
EOF
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# Use a custom Dockerfile with an ancient version of su.
jtest_prepare "cqfd run with su -c sets path"
echo "FROM ubuntu:16.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# Use another custom Dockerfile with a recent version of su.
jtest_prepare "cqfd run with su --session-command sets path"
echo "FROM ubuntu:24.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# Install the sudo package.
jtest_prepare "cqfd run with sudo sets path"
echo "ENV DEBIAN_FRONTEND=noninteractive" >>.cqfd/docker/Dockerfile
echo "RUN apt-get update && apt-get install -y --no-install-recommends sudo" >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# Set user UID and GID.
echo "USER $UID:${GROUPS[0]}" >>.cqfd/docker/Dockerfile
jtest_prepare "cqfd run with sh sets path"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# Restore .cqfdrc and Dockerfile.
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# Restore container.
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
