#!/usr/bin/env bash
#
# validate the behavior of cqfd entrypoint

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.missing_dependencies .cqfd/docker/Dockerfile
cp -f .cqfdrc .cqfdrc.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='true'," .cqfdrc

jtest_prepare "run cqfd run without useradd and groupadd commands should fail"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && ! cqfd; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with useradd and groupadd commands should pass"
echo 'RUN apk add shadow' >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run without CQFD_SHELL command should fail"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && ! CQFD_SHELL=/bin/bash cqfd --verbose; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with CQFD_SHELL command should pass"
echo 'RUN apk add bash' >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && CQFD_SHELL=/bin/bash cqfd --verbose; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with su command should pass"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose \
		| awk -v rc=1 '/Using "su"/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with sudo command should pass"
echo 'RUN apk add sudo' >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose \
		| awk -v rc=1 '/Using "sudo"/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd should create the user"
sed -e "/\[build\]/,/^$/s,^command=.*$,command='grep \"^$USER:x:$UID:${GROUPS[0]}::$HOME:/bin/sh\$\" /etc/passwd'," -i .cqfdrc
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd should create and own the user's home directory"
echo 'RUN sed "/DEFAULT_HOME/s,yes,no," -i /etc/login.defs' >>.cqfd/docker/Dockerfile
sed -e "/\[build\]/,/^$/s,^command=.*$,command='test -w $HOME'," -i .cqfdrc
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && CQFD_NO_USER_SSH_CONFIG=true CQFD_NO_USER_GIT_CONFIG=true cqfd; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd should execute as the host user"
sed -e "/\[build\]/,/^$/s,^command=.*$,command='id'," -i .cqfdrc
if [ "${cqfd_docker[-1]}" = "podman" ] || ! getent group docker | grep -q "$USER"; then
	jtest_result skip
else
	if cqfd | grep "^uid=$UID($USER) gid=${GROUPS[0]}($USER) groups=$UID($USER)$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd should not execute sudo without authentication"
sed -e "/\[build\]/,/^$/s,^command=.*$,command='sudo env'," -i .cqfdrc
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if ! cqfd </dev/null; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd with CQFD_SUDO_NOPASSWD should execute sudo without authentication"
if [ "${cqfd_docker[-1]}" = "podman" ] || ! getent group docker | grep -q "$USER"; then
	jtest_result skip
else
	if CQFD_SUDO_NOPASSWD=true cqfd </dev/null; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd with sudo should preserve umask"
sed -e "/\[build\]/,/^$/s,^command=.*$,command='umask'," -i .cqfdrc
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if umask="$(cqfd)" && \
	   umask_nopasswd="$(CQFD_SUDO_NOPASSWD=true cqfd)" && \
	   [ "$umask" = "$umask_nopasswd" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with ancient su should run su -c"
echo "FROM ubuntu:16.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose \
		| awk -v rc=1 '/Using "su" to execute command/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with recent su should run su --session-command"
echo "FROM ubuntu:24.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose \
		| awk -v rc=1 '/Using "su" to execute session command/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with sudo should run sudo"
echo "ENV DEBIAN_FRONTEND=noninteractive" >>.cqfd/docker/Dockerfile
echo "RUN apt-get update && apt-get install -y --no-install-recommends sudo" >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose \
		| awk -v rc=1 '/Using "sudo" to execute command/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# restore .cqfdrc and Dockerfile
mv -f .cqfdrc.orig .cqfdrc
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
