#!/usr/bin/env bash
#
# validate the behavior of init with alternate config file and directory
# validate the behavior of init with alternate config file, directory and
# worktree

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

################################################################################
# First, move every local cqfd files into an external directory and use
# alternate filenames
################################################################################
cqfdrc_old=$(mktemp)
cp -f .cqfdrc "$cqfdrc_old"
extdir="external/dir"
mkdir -p "$extdir"
mv .cqfd "$extdir/"
sed -e "/\[build\]/,/^$/s,^command=.*$,command=\"echo 'I am .cqfdrc'\"," "$cqfdrc_old" >"$extdir/.cqfdrc"
sed -e "/\[build\]/,/^$/s,^command=.*$,command=\"echo 'I am Cqfdfile\"," "$cqfdrc_old" >Cqfdfile
touch local-directory
touch "$extdir/alternate-directory"
cqfd="$TDIR/$extdir/.cqfd/cqfd"

################################################################################
# 'cqfd init' without local files should fail
################################################################################
jtest_prepare "cqfd init without local files should fail"
if ! "$cqfd" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# cqfd changing to alternate working directory should work
################################################################################
jtest_prepare "cqfd changing to alternate working directory should work"
if "$cqfd" -C "$extdir" init && \
   "$cqfd" -C "$extdir" run "test -e alternate-directory"; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# cqfd using alternate directory map alternate directory as worktree
################################################################################
jtest_prepare "cqfd specifying a cqfd directory map directory as worktree"
if "$cqfd" -d "$extdir/.cqfd" init && \
   "$cqfd" -d "$extdir/.cqfd" run "test -e $extdir/alternate-directory" && \
   "$cqfd" -d "$extdir/.cqfd" run "! test -e local-directory"; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# cqfd using alternate directory and worktree map worktree as worktree
################################################################################
jtest_prepare "cqfd specifying a cqfd directory and worktree map worktree"
if "$cqfd" -d "$extdir/.cqfd" init && \
   "$cqfd" -d "$extdir/.cqfd" run "test -e $extdir/alternate-directory" && \
   "$cqfd" -d "$extdir/.cqfd" -w "$PWD" run "test -e local-directory"; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# cqfd using alternate directory and worktree map worktree as worktree
################################################################################
jtest_prepare "cqfd specifying a cqfd directory and worktree map worktree"
if "$cqfd" -d "$extdir/.cqfd" init && \
   "$cqfd" -d "$extdir/.cqfd" run "test -e $extdir/alternate-directory" && \
   "$cqfd" -d "$extdir/.cqfd" -w "$PWD" run "test -e local-directory"; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# cqfd using alternate directory and worktree map worktree as worktree
################################################################################
jtest_prepare "cqfd specifying a cqfd directory and worktree map worktree"
if "$cqfd" -d "$extdir/.cqfd" init && \
   "$cqfd" -d "$extdir/.cqfd" run "test -e $extdir/alternate-directory" && \
   "$cqfd" -d "$extdir/.cqfd" -w "$PWD" run "test -e local-directory"; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using absolute
# filenames should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using relative filenames using options should work"
if "$cqfd" -d "$extdir/cqfd" -f "$extdir/cqfdrc" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using absolute
# filenames should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using absolute using options filenames should work"
if "$cqfd" -d "$PWD/$extdir/cqfd" -f "$PWD/$extdir/cqfdrc" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using filenames
# should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using filenames using environment variables should work"
if CQFD_DIR=cqfd CQFDRC_FILE=cqfdrc "$cqfd" -C "$extdir" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using absolute
# filenames should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using relative filenames using environment variables should work"
if CQFD_DIR="$extdir/cqfd" CQFDRC_FILE="$extdir/cqfdrc" "$cqfd" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' using alternate filenames in an external directory using absolute
# filenames should work
################################################################################
jtest_prepare "cqfd init using alternate filenames in an external directory using absolute filenames using environment variables should work"
if CQFD_DIR="$PWD/$extdir/cqfd" CQFDRC_FILE="$PWD/$extdir/cqfdrc" "$cqfd" init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# restore local cqfd files
################################################################################
rm -f "$extdir/alternate-directory"
rm -f local-directory
rm -f Cqfdfile
rm -f "$extdir/.cqfdrc"
mv "$extdir/.cqfd" .
rmdir -p "$extdir"
mv -f "$cqfdrc_old" .cqfdrc
