#!/usr/bin/env bash
#
# validate the behavior of run -c command with flavors

. "$(dirname "$0")/jtest.inc" "$1"
flavor="foo"
test_file="$flavor"
test_run_c_file="test_run_c.txt"
fail=0

cd "$TDIR/" || exit 1

if [ -f "$test_file" ] || [ -f "$test_run_c_file" ]; then
	jtest_log info "$test_file or $test_run_c_file already present before test, removing..."
	rm -f "$test_file"
	rm -f "$test_run_c_file"
fi

jtest_prepare "build cmd for '$flavor' flavor and concatenate with an additional option"
if ! cqfd -b "$flavor" run -c --debug >>"$test_run_c_file"; then
	jtest_log fatal "cqfd run -c --debug failed"
	fail=1
fi

# at the end of this test, $test_run_c_file is populated
if ! grep "^Successfully remade target file 'foo'\.$" "$test_run_c_file"; then
	jtest_log fatal "$test_run_c_file not present after test"
	fail=1
	rm -f "$test_run_c_file"
fi

# at the end of either test, $test_file is populated
if ! grep "^cqfd$" "$test_file"; then
	jtest_log fatal "$test_file not present after test"
	fail=1
	rm -f "$test_file"
fi

if [ "$fail" -eq 0 ]; then
	jtest_result pass
else
	jtest_result fail
fi

rm -f "$test_file"
rm -f "$test_run_c_file"
