#!/usr/bin/env bash
#
# validate the behavior of init with docker extra build arguments

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup Dockerfile
mv .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

cp .cqfd/docker/Dockerfile.init_extra_env .cqfd/docker/Dockerfile

jtest_prepare "run cqfd init with ARG in Dockerfile and without CQFD_EXTRA_BUILD_ARGS and docker_build_args should fail"
if ! cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with ARG in Dockerfile and with CQFD_EXTRA_BUILD_ARGS should pass"
if CQFD_EXTRA_BUILD_ARGS="--build-arg FOO=foo --no-cache" cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

jtest_prepare "run cqfd init with ARG in Dockerfile and with docker_build_args should pass"
sed -e '/\[build\]/adocker_build_args="--build-arg FOO=foo --no-cache"' .cqfdrc.orig >.cqfdrc
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

# restore .cqfdrc and Dockerfile
mv .cqfdrc.orig .cqfdrc
mv .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
