#!/usr/bin/env bash
#
# validate the behavior of dependencies

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.missing_dependencies .cqfd/docker/Dockerfile

jtest_prepare "run cqfd run without useradd and groupadd commands should fail"
if cqfd init && ! cqfd run; then
	jtest_result pass
else
	jtest_result fail
fi

echo 'RUN apk add shadow' >>.cqfd/docker/Dockerfile

jtest_prepare "run cqfd run with useradd and groupadd commands should pass"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose run true; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

echo 'RUN apk add bash' >>.cqfd/docker/Dockerfile

jtest_prepare "run cqfd run with CQFD_SHELL command should pass"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && CQFD_SHELL=/bin/bash cqfd --verbose run true; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with su command should pass"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose run true \
		| awk -v rc=1 '/Using "su"/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

echo 'RUN apk add sudo' >>.cqfd/docker/Dockerfile

jtest_prepare "run cqfd run with sudo command should pass"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd --verbose run true \
		| awk -v rc=1 '/Using "sudo"/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run should create the user"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run "grep \"^$USER:x:$UID:${GROUPS[0]}::$HOME:/bin/sh\$\" /etc/passwd"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

echo 'RUN sed "/DEFAULT_HOME/s,yes,no," -i /etc/login.defs' >>.cqfd/docker/Dockerfile

jtest_prepare "run cqfd run should create and own the user's home directory"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && CQFD_NO_USER_SSH_CONFIG=true CQFD_NO_USER_GIT_CONFIG=true cqfd run "test -w $HOME"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run should execute as the host user"
if [ "${cqfd_docker[-1]}" = "podman" ] || ! getent group docker | grep -q "$USER"; then
	jtest_result skip
else
	if cqfd run id | grep "^uid=$UID($USER) gid=${GROUPS[0]}($USER) groups=$UID($USER)$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run should not execute sudo without authentication"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if ! cqfd run "sudo env" </dev/null; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with CQFD_SUDO_NOPASSWD should execute sudo without authentication"
if [ "${cqfd_docker[-1]}" = "podman" ] || ! getent group docker | grep -q "$USER"; then
	jtest_result skip
else
	if CQFD_SUDO_NOPASSWD=true cqfd run "sudo env" </dev/null; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with sudo should preserve umask"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if umask="$(cqfd run "umask")" && \
	   umask_nopasswd="$(CQFD_SUDO_NOPASSWD=true cqfd run "umask")" && \
	   [ "$umask" = "$umask_nopasswd" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# restore initial Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
