#!/usr/bin/env bash
#
# validate the behavior -c option

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.cqfd/cqfd"
flavor="foo"
test_file="$flavor"
test_c_file="test_c.txt"
fail=0

cd "$TDIR/" || exit 1

if [ -f "$test_file" ] || [ -f "$test_c_file" ]; then
	jtest_log info "$test_file or $test_c_file already present before test, removing..."
	rm -f "$test_file"
	rm -f "$test_c_file"
fi

jtest_prepare "cqfd -c with a given '$flavor' flavor concatenate additional option"
if ! "$cqfd" -b "$flavor" -c --debug >"$test_c_file"; then
	jtest_log fatal "cqfd -c --debug failed"
	fail=1
	rm -f "$test_c_file"
fi

# at the end of this test, $test_c_file is populated
if ! grep -qw "target 'foo'" "$test_c_file"; then
	jtest_log fatal "$test_c_file not present after test"
	fail=1
	rm -f "$test_c_file"
fi

# at the end of either test, $test_file is populated
if ! grep -qw "cqfd" "$test_file"; then
	jtest_log fatal "$test_file not present after test"
	fail=1
	rm -f "$test_file"
fi

if [ "$fail" -eq 0 ]; then
	jtest_result pass
else
	jtest_result fail
fi

rm -f "$test_file"
rm -f "$test_c_file"
