#!/usr/bin/env bash
#
# validate the behavior of cqfd with user_extra_groups

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='groups'," .cqfdrc

jtest_prepare "run cqfd with groups in environment user_extra_groups should execute as groups"
if [ "$USER" = "runner" ] || [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if user_extra_groups="docker newgroup:12345" cqfd | grep docker | grep newgroup; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd with groups in user_extra_groups should execute as groups"
if [ "$USER" = "runner" ] || [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	echo 'user_extra_groups="docker newgroup:12345"' >>.cqfdrc
	if cqfd | grep docker | grep newgroup; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
