#!/usr/bin/env bash
#
# validate the behavior of cqfd image

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

# backup .cqfd and .cqfdrc
mv .cqfd .cqfd.orig
cp .cqfdrc .cqfdrc.orig

cp cqfdrc-image .cqfdrc

image="ubuntu:16.04"
if "${cqfd_docker[@]}" inspect "$image" &>/dev/null; then
	jtest_log info "${cqfd_docker[-1]} registry contains image named: $image, removing..."
	if ! "${cqfd_docker[@]}" rmi "$image"; then
		jtest_log error "removing image failed"
	fi
fi

jtest_prepare "run cqfd init should pull image $image from remote registry"
if cqfd init && \
   "${cqfd_docker[@]}" inspect "$image" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd should run pulled image $image from local registry"
if cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore .cqfdrc and .cqfd
mv .cqfdrc.orig .cqfdrc
mv .cqfd.orig .cqfd

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
