#!/usr/bin/env bash
#
# validate the behavior of run with alternate file

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

extdir="external/dir"
mkdir -p "$extdir"

# move .cqfdrc
mv .cqfdrc "$extdir/cqfdrc"

jtest_prepare "run cqfd run without argument and with option -f should pass"
if cqfd -f "$extdir/cqfdrc" run && test -f a/cqfd_a.txt; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
make clean

jtest_prepare "run cqfd run with argument and option -f should pass"
if cqfd -f "$extdir/cqfdrc" run "touch file" && test -f file; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm file

# moveback .cqfdrc
mv "$extdir/cqfdrc" .cqfdrc

# cleanup
rmdir -p "$extdir"
