#!/usr/bin/env bash
#
# validate the behavior of run with Dockerfile

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup Dockerfile
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "cqfd run using a Dockerfile with entrypoint should success"
cat <<EOF >>.cqfd/docker/Dockerfile
ENTRYPOINT ["false"]
EOF
if cqfd init && cqfd run; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd run using a Dockerfile with workdir should success"
cat <<EOF >>.cqfd/docker/Dockerfile
WORKDIR /mnt
EOF
if cqfd init && cqfd run pwd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
make clean

# restore initial Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
