#!/usr/bin/env bash
#
# validate the behavior of run with working directory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

workdir="workingdir"
mkdir -p "$workdir"
mv .cqfd "$workdir/.cqfd"
mv .cqfdrc "$workdir/.cqfdrc"

cd "$workdir" || exit 1

jtest_prepare "run cqfd run with --working-directory set to inexistant directory should fail"
if ! cqfd -w "nonexistentdir" run; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run without --working-directory should own working directory and should not own its parent directory"
if cqfd run "stat -c '%u' ." | grep "^$UID$" && \
   cqfd run "stat -c '%u' .." | grep "^0$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --working-directory set to parent directory should own parent directory and should not own its parent directory"
if cqfd -w ".." run "stat -c '%u' ." | grep "^$UID$" && \
   cqfd -w ".." run "stat -c '%u' .." | grep "^0$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with CQFD_WORKDIR set to inexistant directory should fail"
if ! CQFD_WORKDIR="nonexistentdir" cqfd run; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with CQFD_WORKDIR set to parent directory should own parent directory and should not own its parent directory"
if CQFD_WORKDIR=".." cqfd run "stat -c '%u' ." | grep "^$UID$" && \
   CQFD_WORKDIR=".." cqfd run "stat -c '%u' .." | grep "^0$"; then
	jtest_result pass
else
	jtest_result fail

fi

jtest_prepare "run cqfd run with CQFD_WORKDIR set to parent directory using absolute path should own parent directory and should not own its parent directory"
if CQFD_WORKDIR="$PWD/.." cqfd run "stat -c '%u' ." | grep "^$UID$" && \
   CQFD_WORKDIR="$PWD/.." cqfd run "stat -c '%u' .." | grep "^0$"; then
	jtest_result pass
else
	jtest_result fail

fi

# restore local cqfd files
cd "$OLDPWD" || exit 1
mv "$workdir/.cqfdrc" .cqfdrc
mv "$workdir/.cqfd" .cqfd
rmdir -p "$workdir"
