#!/usr/bin/env bash
#
# validate the behavior of run command with flavors

. "$(dirname "$0")/jtest.inc" "$1"
flavor="foo"

cd "$TDIR/" || exit 1

# First pass: build a simple flavor
test_file=$flavor
jtest_prepare "cqfd build cmd for '$flavor' flavor"

# shellcheck disable=SC2181
if cqfd -b "$flavor" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_log log "failed or test file not present after execution"
	jtest_result fail
fi
rm -f "$test_file"

# Second pass: override flavor build with an additional command
test_file=$flavor
jtest_prepare "cqfd run build cmd for '$flavor' flavor"

# shellcheck disable=SC2181
if cqfd -b "$flavor" run && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_log log "failed or test file not present after execution"
	jtest_result fail
fi
rm -f "$test_file"

# cleanup
make clean
