#!/usr/bin/env bash
#
# validate the behavior of run command

. "$(dirname "$0")/jtest.inc" "$1"
test_file="a/cqfd_a.txt"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd run without argument should pass"
# shellcheck disable=SC2181
if cqfd && grep -qw "^cqfd$" "$test_file"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
rm -f "$test_file"

jtest_prepare "run cqfd run with run without arguments should pass"
# shellcheck disable=SC2181
if cqfd run && grep -qw "^cqfd$" "$test_file"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
rm -f "$test_file"

jtest_prepare "run cqfd run with outdated Dockerfile should fail"
dockerfile=.cqfd/docker/Dockerfile
echo "RUN echo $RANDOM" >>"$dockerfile"
if ! cqfd run; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
make clean
# restore Dockerfile
sed -i '$d' "$dockerfile"
