#!/usr/bin/env bash
#
# validate the behavior of init command with flavors

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='grep ^NAME /etc/os-release'," .cqfdrc
sed -i -e "/\[foo\]/,/^$/s,^command=.*$,command='grep ^NAME /etc/os-release'," .cqfdrc
sed -i -e "s/\[foo\]/[foo]\ndistro='centos'/" .cqfdrc

jtest_prepare "run cqfd init with build flavor should pass"
if cqfd -b foo init && \
   cqfd -b foo | grep "^NAME=\"CentOS Linux\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with nonexistent build flavor should fail"
if ! cqfd -b foobar init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init without build flavor should pass"
if cqfd init && \
   cqfd | grep "^NAME=\"Ubuntu\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
