#!/usr/bin/env bash
#
# validate the behavior of cqfd with docker extra pull arguments

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
cp -f cqfdrc-image .cqfdrc

jtest_prepare "run cqfd init with CQFD_EXTRA_PULL_ARGS should pass"
if CQFD_EXTRA_BUILD_ARGS="--disable-content-trust=false" cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with docker_pull_args should pass"
sed '/\[build\]/adocker_build_args="--disable-content-trust=false"' -i .cqfdrc
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
