#!/usr/bin/env bash
#
# validate the behavior of cqfd from subdirectory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='pwd'," .cqfdrc

subdir="dir with space/b/c/d/e"
mkdir -p "$subdir"
cd "$subdir" || exit 1

jtest_prepare "run cqfd from project's subdirectory should pass"
if cqfd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
cd "$OLDPWD" || exit 1

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc

mv -f Makefile .cqfd .cqfdrc "$subdir"

cd "$subdir" || exit 1

jtest_prepare "run cqfd from a subdirectory containing spaces should pass"
if cqfd && test -f a/cqfd_a.txt; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
make clean

# teardown
cd "$OLDPWD" || exit 1

# restore local cqfd files
mv -f "$subdir/.cqfdrc" "$subdir/.cqfd" "$subdir/Makefile" .

# cleanup
rmdir -p "$subdir"
