#!/usr/bin/env bash
#
# validate the behavior of custom_img_name

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.init_custom_image .cqfd/docker/Dockerfile
cp -f .cqfdrc .cqfdrc.orig
cp -f cqfdrc-custom_image .cqfdrc

custom_img_name="ubuntu:16.04"
sed -i -e "s!^custom_img_name=.*\$!custom_img_name='$custom_img_name'!" .cqfdrc
if "${cqfd_docker[@]}" inspect "$custom_img_name" &>/dev/null; then
	jtest_log info "${cqfd_docker[-1]} registry contains image named: $custom_img_name, removing..."
	"${cqfd_docker[@]}" rmi "$custom_img_name"
fi

jtest_prepare "run cqfd should pull image $custom_img_name from registry"
if cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

custom_img_name="cqfd_test_custom_image_$RANDOM$RANDOM"
sed -i -e "s!^custom_img_name=.*\$!custom_img_name='$custom_img_name'!" .cqfdrc
if "${cqfd_docker[@]}" inspect "$custom_img_name" &>/dev/null; then
	jtest_log info "${cqfd_docker[-1]} registry contains image named: $custom_img_name, removing..."
	"${cqfd_docker[@]}" rmi "$custom_img_name"
fi

jtest_prepare "run cqfd should fail to pull inexistant image $custom_img_name from remote registry"
if ! cqfd; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init should create image $custom_img_name from Dockerfile"
if cqfd init && \
   "${cqfd_docker[@]}" inspect "$custom_img_name" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd should run created image $custom_img_name from local registry"
if cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 24.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
"${cqfd_docker[@]}" rmi "$custom_img_name"

# restore initial .cqfdrc and Dockerfile
mv -f .cqfdrc.orig .cqfdrc
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
