#!/usr/bin/env bash
#
# validate the behavior of cqfd from subdirectory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='pwd'," .cqfdrc

sub_dir="dir with space/b/c/d/e"
mkdir -p "$sub_dir"
pushd "$sub_dir" >/dev/null || exit 1

jtest_prepare "run cqfd from project's subdirectory should pass"
if cqfd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
popd >/dev/null || exit 1
rmdir -p "$sub_dir"

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
