#!/usr/bin/env bash
#
# validate the resiliency of cqfd against whitespaces

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.cqfd/cqfd"

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd' passes environment variables to the container when using
# CQFD_EXTRA_RUN_ARGS with an option containing a whitespace
################################################################################
jtest_prepare "cqfd with an option containing whitespace in CQFD_EXTRA_RUN_ARGS"
if CQFD_EXTRA_RUN_ARGS="-e FOO=bar\ baz" \
	"$cqfd" env | grep "FOO=bar baz"; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd' passes environment variables to the container when using
# docker_run_args with an option containing a whitespace
################################################################################
jtest_prepare "cqfd with an option containing whitespace in docker_run_args"
# setup -- add the docker_run_args option to config
sed '/\[build\]/adocker_run_args="-e FOO=bar\\ baz"'\
    -i "$TDIR/.cqfdrc"
if "$cqfd" env | grep "FOO=bar baz"; then
	jtest_result pass
else
	jtest_result fail
fi

# teardown -- clear the docker_run_args option from config
sed '/\[build\]/{n;d}' -i "$TDIR/.cqfdrc"
