#!/usr/bin/env bash
#
# validate the behavior of cqfd from subdirectory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup .cqfdrc
cp .cqfdrc .cqfdrc.orig

sed -e "/\[build\]/,/^$/s,^command=.*$,command='pwd'," -i .cqfdrc

subdir="dir with space/b/c/d/e"
mkdir -p "$subdir"
cd "$subdir" || exit 1

jtest_prepare "run cqfd from project's subdirectory should pass"
if cqfd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
cd "$OLDPWD" || exit 1

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc

# move Makefile, .cqfd and .cqfdrc
mv Makefile .cqfd .cqfdrc "$subdir"

cd "$subdir" || exit 1

jtest_prepare "run cqfd from a subdirectory containing spaces should pass"
if cqfd && test -f a/cqfd_a.txt; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
make clean

# teardown
cd "$OLDPWD" || exit 1

# moveback .cqfdrc, .cqfd and Makefile
mv "$subdir/.cqfdrc" "$subdir/.cqfd" "$subdir/Makefile" .

# cleanup
rmdir -p "$subdir"
