#!/usr/bin/env bash
#
# validate the behavior of run command with extra groups

set -o pipefail

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
cqfd_docker="${CQFD_DOCKER:-docker}"

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd run' should add extra_groups provided by an environment variable
################################################################################
jtest_prepare "'cqfd run' should add extra_groups provided by an env variable"
if [ "$USER" = "runner" ] || [ "$cqfd_docker" = "podman" ]; then
	jtest_result skip
else
	output=$(user_extra_groups="docker newgroup:12345" "$cqfd" run groups | grep docker | grep newgroup)
	if [ -n "$output" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# 'cqfd run' should add extra_groups provided by the config
################################################################################
jtest_prepare "'cqfd run' should add config's extra_groups to the local user"
if [ "$USER" = "runner" ] || [ "$cqfd_docker" = "podman" ]; then
	jtest_result skip
else
	cp -f .cqfdrc .cqfdrc.old
	echo 'user_extra_groups="docker newgroup:12345"' >>.cqfdrc
	output=$("$cqfd" run groups | grep docker | grep newgroup)
	if [ -n "$output" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
	# restore initial .cqfdrc
	mv -f .cqfdrc.old .cqfdrc
fi
