#!/usr/bin/env bash
#
# validate the behavior of run -c command

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd run -c without argument should fail"
if ! cqfd run -c; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run -c with argument should concatenate to command string"
if cqfd run -c --debug | grep "^Successfully remade target file 'build'\.$"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
make clean

jtest_prepare "run cqfd run -c with argument and --build flavor should concatenate to command string"
if cqfd -b foo run -c --debug | grep "^Successfully remade target file 'foo'\.$" && \
   grep "^cqfd$" foo; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
rm -f foo
