#!/usr/bin/env bash
#
# validate the behavior of run command

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig

jtest_prepare "run cqfd run without argument should pass"
# shellcheck disable=SC2181
if cqfd && test -e a/cqfd_a.txt; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f a/cqfd_a.txt

jtest_prepare "run cqfd run with run without arguments should pass"
# shellcheck disable=SC2181
if cqfd run && test -e a/cqfd_a.txt; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f a/cqfd_a.txt

jtest_prepare "run cqfd run with outdated Dockerfile should fail"
echo "RUN echo $RANDOM" >>.cqfd/docker/Dockerfile
if ! cqfd run; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
make clean

# restore initial Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

jtest_prepare "run cqfd run with argument should run command string"
# shellcheck disable=SC2181
if cqfd run "touch foobar" && test -f foobar; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f foobar

jtest_prepare "run cqfd run with arguments should run as a command string"
# shellcheck disable=SC2181
if cqfd run touch foobar && test -f foobar; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f foobar

jtest_prepare "run cqfd run with arguments cannot preserve arguments"
# shellcheck disable=SC2016
if cqfd run /bin/sh -c 'printf "0=$0,*=$*,#=$#"' zero one two three | grep "^0=sh,\*=,#=0$"; \
   test "${PIPESTATUS[0]}" -eq 2; then
	jtest_result pass
else
	jtest_result fail
fi

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
