#!/usr/bin/env bash
#
# validate the behavior of run command with extra arguments

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
test_file="file.$RANDOM"

cd "$TDIR/" || exit 1

# First pass: the command is a single argument
# Data set shall produce $test_file:

if [ -f "$test_file" ]; then
	jtest_log fatal "$test_file already present before test"
	rm -f "$test_file"
	continue
fi

jtest_prepare "cqfd run \"touch somefile\" creates the file"
cqfd run "touch $test_file"

# shellcheck disable=SC2181
if [ "$?" -eq 0 ] && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_log fatal "failed or test file not present after execution"
	jtest_result fail
fi
rm -f "$test_file"

# Second pass: the command is the rest of the arguments
# Data set shall produce $test_file:

jtest_prepare "cqfd run touch somefile (no quotes) creates the file"
cqfd run touch "$test_file"

# shellcheck disable=SC2181
if [ "$?" -eq 0 ] && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_log fatal "failed or test file not present after execution"
	jtest_result fail
fi
rm -f "$test_file"

jtest_prepare "cqfd run with additional argument, do not preserve the arguments"
# shellcheck disable=SC2016
if cqfd run /bin/sh -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "^0=sh,\*=,#=0$"; \
   test "${PIPESTATUS[0]}" -eq 2; then
	jtest_result pass
else
	jtest_result fail
fi
