#!/usr/bin/env bash
#
# validate the behavior of run command with alternative config file

. "$(dirname "$0")/jtest.inc" "$1"
confdir=".config/dir"
flavor="foo"

cd "$TDIR/" || exit 1

# cp the default conf and replace the original with a fake one
mkdir -p "$confdir"
mv .cqfdrc "$confdir/mycqfdrc"

# First pass: run with non default config file
test_file="a/cqfd_a.txt" # from mycqfdrc
jtest_prepare "cqfd run with config in $confdir/mycqfdrc"
if cqfd -f "$confdir/mycqfdrc" run && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

# Second pass: run with non default config file and bash cmd
test_file="file.$RANDOM"
jtest_prepare "cqfd run and override with additionnal cmd"
if cqfd -f "$confdir/mycqfdrc" run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

# Third pass: run with non default config file and flavor
test_file="$flavor.$RANDOM"
jtest_prepare "cqfd run and build a given '$flavor' flavor"
if cqfd -f "$confdir/mycqfdrc" -b "$flavor" run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

# Fourth pass: run with flavor non default config file
test_file="$flavor.$RANDOM"
jtest_prepare "cqfd run and build a given '$flavor' flavor (inverted args)"
if cqfd -b "$flavor" -f "$confdir/mycqfdrc" run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

# restore initial .cqfdrc
mv -f "$confdir/mycqfdrc" .cqfdrc

# cleanup
make clean
rmdir -p "$confdir"
