#!/usr/bin/env bash
#
# validate the behavior of init command with flavors

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
flavor="foo"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
sed -i -e "s/\[foo\]/[foo]\ndistro='centos'/" .cqfdrc

jtest_prepare "run cqfd init with build flavor '$flavor' should pass"
if cqfd -b "$flavor" init && \
   cqfd -b "$flavor" run "grep '^NAME=' /etc/os-release" | grep "^NAME=\"CentOS Linux\"$"; then
	jtest_result pass
else
	jtest_result fail
fi
# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc

flavorPart="${flavor:0:2}"
jtest_prepare "run cqfd init with nonexistent build flavor '$flavor' should fail"
if ! cqfd -b "$flavorPart" init; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init without build flavor should pass"
if cqfd init &&
   cqfd run "grep '^NAME=' /etc/os-release" | grep "^NAME=\"Ubuntu\"$"; then
	jtest_result pass
else
	jtest_result fail
fi
