#!/usr/bin/env bash
#
# validate the behavior of cqfd with path

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

mv -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
mv -f .cqfdrc .cqfdrc.orig

jtest_prepare "run cqfd run with path and busybox su -c should set PATH"
sed '/\[build\]/apath="/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin"' .cqfdrc.orig >.cqfdrc
cat <<EOF >.cqfd/docker/Dockerfile
FROM alpine:3.20
RUN apk update && apk upgrade
RUN apk add shadow
EOF
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with busybox su -c should preserve umask"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if umask="$(cqfd --cqfdrc-file .cqfdrc.orig run "umask")" && \
	   umask_path="$(cqfd run "umask")" && \
	   [ "$umask" = "$umask_path" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with path and su -c should set PATH"
echo "FROM ubuntu:16.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with su -c should preserve umask"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if umask="$(cqfd --cqfdrc-file .cqfdrc.orig run "sh -c umask")" && \
	   umask_path="$(cqfd run "sh -c umask")" && \
	   [ "$umask" = "$umask_path" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with path and su --session-command should set PATH"
echo "FROM ubuntu:24.04" >.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with su --session-command should preserve umask"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if umask="$(cqfd --cqfdrc-file .cqfdrc.orig run "umask")" && \
	   umask_path="$(cqfd run "umask")" && \
	   [ "$umask" = "$umask_path" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with path and sudo should set PATH"
echo "ENV DEBIAN_FRONTEND=noninteractive" >>.cqfd/docker/Dockerfile
echo "RUN apt-get update && apt-get install -y --no-install-recommends sudo" >>.cqfd/docker/Dockerfile
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with sudo should preserve umask"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if umask="$(cqfd --cqfdrc-file .cqfdrc.orig run "umask")" && \
	   umask_path="$(cqfd run "umask")" && \
	   [ "$umask" = "$umask_path" ]; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

echo "USER $UID:${GROUPS[0]}" >>.cqfd/docker/Dockerfile
jtest_prepare "run cqfd with path and sh should set PATH"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
else
	if cqfd init && cqfd run env | grep "^PATH=/opt/cqfd/bin:/usr/sbin:/usr/bin:/sbin:/bin$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# restore .cqfdrc and Dockerfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile
mv -f .cqfdrc.orig .cqfdrc

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
