#!/usr/bin/env bash
#
# validate the resiliency of cqfd run against whitespaces

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd run with --env containing whitespaces in CQFD_EXTRA_RUN_ARGS should set environment variables and preserve whitespaces"
if CQFD_EXTRA_RUN_ARGS="-e FOO=bar\ baz" \
   cqfd run env | grep "^FOO=bar baz$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --env containing whitespaces in docker_run_args should set environment variables and preserve whitespaces"
sed '/\[build\]/adocker_run_args="-e FOO=bar\\ baz"'\
    -i "$TDIR/.cqfdrc"
if cqfd run env | grep "^FOO=bar baz$"; then
	jtest_result pass
else
	jtest_result fail
fi

# teardown -- clear the docker_run_args option from config
sed '/\[build\]/{n;d}' -i "$TDIR/.cqfdrc"
