#!/usr/bin/env bash
#
# validate the sanitization of image name

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig

################################################################################
# 'cqfd init' creates image with invalid user name should pass
################################################################################
dh="$(sha256sum .cqfd/docker/Dockerfile | cut -b 1-7)"
image="cqfd-user_invalid-cqfd-test-linux_amd64-docker"
if uname -m | grep -q "^aarch64$"; then
	image="cqfd-user_invalid-cqfd-test-linux_arm64-docker"
fi
if "${cqfd_docker[@]}" inspect "$image:$dh" &>/dev/null; then
	jtest_log info "${cqfd_docker[-1]} registry contains image named: $image:$dh, removing..."
	"${cqfd_docker[@]}" rmi "$image:$dh"
fi

jtest_prepare "run cqfd init with invalid character in USER should create image"
if USER="user@invalid" cqfd init && \
   "${cqfd_docker[@]}" inspect "$image:$dh" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
"${cqfd_docker[@]}" rmi "$image:$dh"

################################################################################
# 'cqfd init' creates image with invalid character in project.org should pass
################################################################################
jtest_prepare "run cqfd init with invalid character in org should create image"
sed -e "s!^org=.*\$!org='savoirfairelinux@invalid'!" .cqfdrc.orig >.cqfdrc
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd init' creates image with invalid character in project.name should pass
################################################################################
jtest_prepare "run cqfd init with invalid character in name should create image"
sed -e "s!^name=.*\$!name='test@invalid'!" .cqfdrc.orig >.cqfdrc
if cqfd init; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Restore initial .cqfdrc
################################################################################
mv -f .cqfdrc.orig .cqfdrc
