#!/usr/bin/env bash
#
# validate the behavior of cqfd with home directory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo \$HOME'," .cqfdrc

jtest_prepare "run cqfd run should set user's HOME environment variable"
# shellcheck disable=SC2016
if cqfd | grep "^$HOME$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --env in CQFD_EXTRA_RUN_ARGS including HOME should set overriden HOME environment variable"
val1="value-$RANDOM"
val2="value-$RANDOM"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo -n \$FOO \$HOME'," .cqfdrc
# shellcheck disable=SC2016
if CQFD_EXTRA_RUN_ARGS="-e FOO=$val1 -e HOME=$val2" cqfd | grep "^$val1 $val2$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --env HOME in CQFD_EXTRA_RUN_ARGS should set overriden HOME environment variable"
val1="value-$RANDOM"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo \$HOME'," .cqfdrc
# shellcheck disable=SC2016
if CQFD_EXTRA_RUN_ARGS="-e HOME=$val1" cqfd | grep "^$val1$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --env in CQFD_EXTRA_RUN_ARGS including JAVA_HOME and HOME should set overriden HOME environment variable"
val1="value-$RANDOM"
val2="value-$RANDOM"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo -n \$JAVA_HOME \$HOME'," .cqfdrc
# shellcheck disable=SC2016
if CQFD_EXTRA_RUN_ARGS="-e JAVA_HOME=$val1 -e HOME=$val2" cqfd | grep "^$val1 $val2$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run should set home directory to passwd file"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='grep -E \"^$USER:x:[[:digit:]]+:[[:digit:]]+:.*:\$HOME:/bin/sh$\" /etc/passwd'," .cqfdrc
if [ "${cqfd_docker[0]}" = "sudo" ] || [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd run with --env in docker_run_args including HOME should set overriden HOME environment variable"
val1="value-$RANDOM"
val2="value-$RANDOM"
cat .cqfdrc.orig - <<EOF >.cqfdrc
docker_run_args="--env FOO=$val1 --env HOME=$val2"
EOF
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo -n \$FOO \$HOME'," .cqfdrc
# shellcheck disable=SC2016
if cqfd | grep "^$val1 $val2$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --env HOME in docker_run_args should set overriden HOME environment variable"
val1="value-$RANDOM"
cat .cqfdrc.orig - <<EOF >.cqfdrc
docker_run_args="--env HOME=$val1"
EOF
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo \$HOME'," .cqfdrc
# shellcheck disable=SC2016
if cqfd | grep "^$val1$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with --env in docker_run_args including JAVA_HOME and HOME should set overriden HOME environment variable"
val1="value-$RANDOM"
val2="value-$RANDOM"
cat .cqfdrc.orig - <<EOF >.cqfdrc
docker_run_args="--env JAVA_HOME=$val1 --env HOME=$val2"
EOF
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='echo -n \$JAVA_HOME \$HOME'," .cqfdrc
# shellcheck disable=SC2016
if cqfd | grep "^$val1 $val2$"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
