#!/usr/bin/env bash
#
# validate the behavior of run command with spaces in current working directory

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

sub_dir="dir with space/b/c/d/e"
mkdir -p "$sub_dir"
mv -f .cqfd .cqfdrc "$sub_dir"
pushd "$sub_dir" >/dev/null || exit 1

jtest_prepare "run cqfd run from a subdirectory containing spaces should pass"
file="rand.$RANDOM"
if cqfd run touch "$file" && [ -f "$file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$file"

# teardown
popd >/dev/null || exit 1

# restore local cqfd files
mv -f "$sub_dir/.cqfdrc" "$sub_dir/.cqfd" .

# cleanup
rmdir -p "$sub_dir"
