#!/usr/bin/env bash
#
# validate the behavior of run command with spaces in current working directory

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

spaces_dir="aa bb cc dd"
spaces_dir2="aa2 bb2 cc2 dd2"
mkdir -p "$spaces_dir/$spaces_dir2"
mv -f .cqfd .cqfdrc "$spaces_dir/$spaces_dir2"
pushd "$spaces_dir/$spaces_dir2" >/dev/null || exit 1

jtest_prepare "run cqfd run from a subdirectory containing spaces should pass"
file="rand.$RANDOM"
if cqfd run touch "$file" && [ -f "$file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$file"

# teardown
popd >/dev/null || exit 1

# restore local cqfd files
mv -f "$spaces_dir/$spaces_dir2/.cqfdrc" "$spaces_dir/$spaces_dir2/.cqfd" .

# cleanup
rmdir -p "$spaces_dir/$spaces_dir2"
