#!/usr/bin/env bash
#
# validate the behavior of cqfd with alternate file and directory, from a subdirectory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

sed -e "/\[build\]/,/^$/s,^command=.*$,command='pwd'," .cqfdrc.orig >.cqfdrc

extdir="external/dir"
mkdir -p "$extdir"

# move .cqfd and .cqfdrc
mv .cqfd "$extdir/cqfd"
mv .cqfdrc "$extdir/cqfdrc"

jtest_prepare "run cqfd from a subdirectory with options -f and -d using path relative to subdirectory should pass"
if cqfd -C "$extdir" -d cqfd -f cqfdrc | grep "^$PWD/$extdir$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with options -f and -d using relative path should pass"
if cqfd -d "$extdir/cqfd" -f "$extdir/cqfdrc" | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with options -f and -d using absolute path should pass"
if cqfd -d "$PWD/$extdir/cqfd" -f "$PWD/$extdir/cqfdrc" | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd from a subdirectory with environments CQFDRC_FILE and CQFD_DIR using relative path to subdirectory should pass"
if CQFD_DIR=cqfd CQFDRC_FILE=cqfdrc cqfd -C "$extdir" | grep "^$PWD/$extdir$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with environments CQFDRC_FILE and CQFD_DIR using relative path should pass"
if CQFD_DIR="$extdir/cqfd" CQFDRC_FILE="$extdir/cqfdrc" cqfd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd from a subdirectory with environments CQFDRC_FILE and CQFD_DIR using absolute path should pass"
if CQFD_DIR="$PWD/$extdir/cqfd" CQFDRC_FILE="$PWD/$extdir/cqfdrc" cqfd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

# moveback .cqfdrc and .cqfd
mv "$extdir/cqfdrc" .cqfdrc
mv "$extdir/cqfd" .cqfd

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc

# cleanup
rmdir -p "$extdir"
