#!/usr/bin/env bash
#
# validate the behavior of init with build flavors

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f Cqfdfile Cqfdfile.orig
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='grep ^NAME /etc/os-release'," Cqfdfile
sed -i -e "/\[foo\]/,/^$/s,^command=.*$,command='grep ^NAME /etc/os-release'," Cqfdfile
sed -i -e "s/\[foo\]/[foo]\ndistro='centos'/" Cqfdfile

jtest_prepare "run cqfd init with build flavor should pass"
if cqfd -b foo init && \
   cqfd -b foo | grep "^NAME=\"CentOS Linux\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd init with nonexistent build flavor should fail"
if ! cqfd -b foobar init; then
	jtest_result pass
else
	jtest_result fail
fi

# restore initial Cqfdfile
mv -f Cqfdfile.orig Cqfdfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
