#!/usr/bin/env bash
#
# validate the behavior of -c command with flavors

. "$(dirname "$0")"/jtest.inc "$1"
cqfd="$TDIR/.cqfd/cqfd"
test_file="a/cqfd_a.txt"
test_c_file="test_c.txt"

cd "$TDIR/" || exit 1

test_setup() {
	if [ -f "$test_file" ] || [ -f "$test_c_file" ]; then
		jtest_log fatal "$test_file or $test_c_file already present before test"
		rm -f "$test_file"
		rm -f "$test_c_file"
	fi
}

test_cleanup() {
	rm -f "$test_file"
	rm -f "$test_c_file"
}

# Append default command build with an additional option
test_step1() {
	jtest_prepare "running \"cqfd -c\" makes it run with appended arguments"
	"$cqfd" -c --debug >> "$test_c_file"

	# at the end of this test, $test_c_file is populated
	if ! grep -qw "target 'build'" "$test_c_file"; then
		jtest_log fatal "$test_c_file not present after test"
		jtest_result fail
		rm -f "$test_c_file"
		return
	fi

	# at the end of either test, $test_file is populated
	if ! grep -qw "cqfd" "$test_file"; then
		jtest_log fatal "$test_file not present after test"
		jtest_result fail
		rm -f "$test_file"
		return
	else
		jtest_result pass
	fi
}
    
# Build the default command with -c
test_step2() {
	jtest_prepare "running \"cqfd -c\" with no argument makes it fail"
	if "$cqfd" -c; then
		jtest_result fail
	else
		jtest_result pass
	fi
}

test_setup
test_step1
test_cleanup

test_setup
test_step2
test_cleanup
