#!/usr/bin/env bash
#
# validate the behavior of dependencies

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.local/bin/cqfd"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

################################################################################
# Use a custom Dockerfile
################################################################################
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.missing_dependencies .cqfd/docker/Dockerfile

################################################################################
# Missing all core dependencies for the launch script
################################################################################
jtest_prepare "cqfd run fails when the Docker image lacks required commands"
if "$cqfd" init && ! "$cqfd" run; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# Add the 'shadow' package, which provides useradd, groupadd.
################################################################################
echo 'RUN apk add shadow' >>.cqfd/docker/Dockerfile

################################################################################
# cqfd run should now be happy with the required commands useradd and groupadd
################################################################################
jtest_prepare "cqfd run with satisfied command useradd and groupadd requirements"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if "$cqfd" init && "$cqfd" --verbose run true; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# Add Bash package.
################################################################################
echo 'RUN apk add bash' >>.cqfd/docker/Dockerfile

################################################################################
# cqfd run should now be happy with the required shell
################################################################################
jtest_prepare "cqfd run with satisfied command shell requirements"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if "$cqfd" init && CQFD_SHELL=/bin/bash "$cqfd" --verbose run true; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# cqfd run should now be happy with the required commands, using su.
################################################################################
jtest_prepare "cqfd run with satisfied command requirements, using su"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if "$cqfd" init && "$cqfd" --verbose run true \
		| awk -v rc=1 '/Using "su"/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# Install the sudo package.
################################################################################
echo 'RUN apk add sudo' >>.cqfd/docker/Dockerfile

################################################################################
# cqfd run should now be happy with the required commands, using sudo
################################################################################
jtest_prepare "cqfd run with satisfied command requirements, using sudo"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if "$cqfd" init && "$cqfd" --verbose run true \
		| awk -v rc=1 '/Using "sudo"/ { rc=0 } 1; END {exit rc}'; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# cqfd run should now creates the user correctly.
################################################################################
jtest_prepare "cqfd run creates the user correctly"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if "$cqfd" init && "$cqfd" run "grep \"^$USER:x:$UID:${GROUPS[0]}::$HOME:/bin/sh\$\" /etc/passwd"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# shadow does not create home directory.
################################################################################
echo 'RUN sed "/DEFAULT_HOME/s,yes,no," -i /etc/login.defs' >>.cqfd/docker/Dockerfile

################################################################################
# cqfd run should now creates and own the user directory.
################################################################################
jtest_prepare "cqfd run creates and owns the user directory"
if [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if "$cqfd" init && CQFD_NO_USER_SSH_CONFIG=true CQFD_NO_USER_GIT_CONFIG=true "$cqfd" run "test -w $HOME"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

################################################################################
# restore initial Dockerfile
################################################################################
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

################################################################################
# restore container
################################################################################
if ! "$cqfd" init; then
	jtest_log error "restore container failed"
fi
