#!/usr/bin/env bash
#
# validate the behavior of cqfd with user_extra_groups

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
read -r -a cqfd_docker <<<"${CQFD_DOCKER:-docker}"
if [ "$CQFD_RUN_WITH_SUDO" = true ]; then
	cqfd_docker=(sudo "${cqfd_docker[@]}")
fi

cd "$TDIR/" || exit 1

# backup .cqfdrc
cp .cqfdrc .cqfdrc.orig
sed -e "/\[build\]/,/^$/s,^command=.*$,command='groups'," -i .cqfdrc
sed -e '/\[build\]/auser_extra_groups="docker newgroup:12345"' -i .cqfdrc

jtest_prepare "run cqfd with groups in user_extra_groups should execute as groups"
if [ "$USER" = "runner" ] || [ "${cqfd_docker[-1]}" = "podman" ]; then
	jtest_result skip
else
	if cqfd | grep docker | grep newgroup; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc
