#!/usr/bin/env bash
#
# validate the behavior of run -c command

. "$(dirname "$0")/jtest.inc" "$1"
test_file="a/cqfd_a.txt"
test_run_c_file="test_run_c.txt"

cd "$TDIR/" || exit 1

# Append default command build with an additional option
jtest_prepare "running \"cqfd run -c\" makes it run with appended arguments"
if ! cqfd run -c --debug >>"$test_run_c_file"; then
	jtest_log fatal "cqfd run -c failed"
	jtest_result fail
	rm -f "$test_run_c_file"
fi

# at the end of this test, $test_run_c_file is populated
if ! grep "^Successfully remade target file 'build'\.$" "$test_run_c_file"; then
	jtest_log fatal "$test_run_c_file not present after test"
	jtest_result fail
	rm -f "$test_run_c_file"
fi

# at the end of either test, $test_file is populated
if grep "^cqfd$" "$test_file"; then
	jtest_result pass
else
	jtest_log fatal "$test_file not present after test"
	jtest_result fail
	rm -f "$test_file"
fi

# cleanup
make clean

rm -f "$test_file"
rm -f "$test_run_c_file"

# Build the default command with run -c
jtest_prepare "running \"cqfd run -c\" with no argument makes it fail"
if ! cqfd run -c; then
	jtest_result pass
else
	jtest_result fail
fi

rm -f "$test_file"
rm -f "$test_run_c_file"
