#!/usr/bin/env bash
#
# validate the behavior of cqfd with Dockerfile

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp .cqfdrc .cqfdrc.orig

jtest_prepare "run cqfd with ENTRYPOINT in Dockerfile should pass"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='true'," .cqfdrc
cat <<EOF >>.cqfd/docker/Dockerfile
ENTRYPOINT ["false"]
EOF
if cqfd init && cqfd; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with WORKDIR in Dockerfile should pass"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='pwd'," .cqfdrc
cat <<EOF >>.cqfd/docker/Dockerfile
WORKDIR /mnt
EOF
if cqfd init && cqfd | grep "^$PWD$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with USER in Dockerfile should pass"
sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='id -un'," .cqfdrc
cat <<EOF >>.cqfd/docker/Dockerfile
USER nobody
EOF
if cqfd init && cqfd | grep "^nobody$"; then
	jtest_result pass
fi

# restore .cqfdrc and Dockerfile
mv .cqfdrc.orig .cqfdrc
mv .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
