#!/usr/bin/env bash
#
# validate the behavior of dockerfile

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

mv -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
mv -f Cqfdfile Cqfdfile.orig

jtest_prepare "run cqfd should use the Dockerfile set in dockerfile"
echo "FROM ubuntu:16.04" >Dockerfile
sed -e "/\[build\]/,/^$/s,^command=.*$,command='grep ^PRETTY_NAME /etc/os-release'," Cqfdfile.orig >Cqfdfile
sed -e '/\[build\]/adockerfile="Dockerfile"' -i Cqfdfile
if cqfd init && \
   cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd from a subdirectory should use the Dockerfile set in dockerfile, relative to project directory"
mkdir -p subdir
if cqfd -C subdir | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd from a subdirectory should use the Dockerfile in subdirectory set in dockerfile"
mkdir -p support/docker
mv Dockerfile support/docker/Dockerfile
sed -e "/\[build\]/,/^$/s,^command=.*$,command='grep ^PRETTY_NAME /etc/os-release'," Cqfdfile.orig >Cqfdfile
sed -e '/\[build\]/adockerfile="support/docker/Dockerfile"' -i Cqfdfile
if cqfd init && \
   cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd from a subdirectory should use the Dockerfile in a subdirectory set in dockerfile, relative to project directory"
if cqfd -C subdir | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -Rf subdir/ support/

jtest_prepare "run cqfd should use the Dockerfile named Containerfile set in dockerfile"
echo "FROM ubuntu:16.04" >.cqfd/docker/Containerfile
sed -e "/\[build\]/,/^$/s,^command=.*$,command='grep ^PRETTY_NAME /etc/os-release'," Cqfdfile.orig >Cqfdfile
sed -e '/\[build\]/adockerfile=".cqfd/docker/Containerfile"' -i Cqfdfile
if cqfd init && \
   cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd should with build_context should use the context directory and the Dockerfile named Containerfile set in dockerfile"
echo "ADD ./Cqfdfile-build_context /tmp/" >>.cqfd/docker/Containerfile
sed -e "/\[build\]/,/^$/s,^command=.*$,command='grep ^PRETTY_NAME /etc/os-release \&\& test -e /tmp/Cqfdfile-build_context'," Cqfdfile.orig >Cqfdfile
sed -e '/\[build\]/adockerfile=".cqfd/docker/Containerfile"' -i Cqfdfile
sed -e '/\[project\]/abuild_context="."' -i Cqfdfile
if cqfd init && \
   cqfd | grep -E "^PRETTY_NAME=\"Ubuntu 16.04(.[[:digit:]]+)? LTS\"$"; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f .cqfd/docker/Containerfile

# restore Cqfdfile and Dockerfile
mv -f Cqfdfile.orig Cqfdfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
