#!/usr/bin/env bash
#
# validate the behavior of run command with alternative config file and build flavors

. "$(dirname "$0")/jtest.inc" "$1"
confdir=".config/dir"
flavor="foo"

cd "$TDIR/" || exit 1

mkdir -p "$confdir"
mv .cqfdrc "$confdir/mycqfdrc"

test_file="a/cqfd_a.txt"
jtest_prepare "run cqfd run without argument and with option -f should pass"
if cqfd -f "$confdir/mycqfdrc" run && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "$test_file"

test_file="file.$RANDOM"
jtest_prepare "run cqfd run with argument and option -f should pass"
if cqfd -f "$confdir/mycqfdrc" run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "$test_file"

test_file="$flavor.$RANDOM"
jtest_prepare "run cqfd run with argument and options -f and -b should pass"
if cqfd -f "$confdir/mycqfdrc" -b "$flavor" run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "$test_file"

test_file="$flavor.$RANDOM"
jtest_prepare "run cqfd run with argument and options -b and -f should pass"
if cqfd -b "$flavor" -f "$confdir/mycqfdrc" run "touch $test_file" && [ -f "$test_file" ]; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "$test_file"

# restore initial .cqfdrc
mv -f "$confdir/mycqfdrc" .cqfdrc

# cleanup
make clean
rmdir -p "$confdir"
