#!/usr/bin/env bash
#
# validate the behavior of run with build flavors

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd without argument and with build flavor should execute flavor's command"
# shellcheck disable=SC2181
if cqfd -b foo && test -f foo; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f foo

jtest_prepare "run cqfd run without argument and with build flavor should execute flavor's command"
# shellcheck disable=SC2181
if cqfd -b foo run && test -f foo; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f foo

jtest_prepare "run cqfd with nonexistent build flavor should fail"
if ! cqfd -b foobar; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd run with nonexistent build flavor should fail"
if ! cqfd -b foobar run; then
	jtest_result pass
else
	jtest_result fail
fi
