#!/usr/bin/env bash
#
# validate the behavior of run -c command with flavors

. "$(dirname "$0")/jtest.inc" "$1"
flavor="foo"
test_file="$flavor"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd run -c with argument and --build flavor should concatenate to command string"
if cqfd -b "$flavor" run -c --debug | grep "^Successfully remade target file 'foo'\.$" && \
   grep "^cqfd$" "$test_file"; then
	jtest_result pass
else
	jtest_result fail
fi

# cleanup
rm -f "$test_file"
