#!/usr/bin/env bash
#
# validate the behavior of CLI

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.cqfd/cqfd"
test_file="a/cqfd_a.txt"

cd "$TDIR/" || exit 1

################################################################################
# 'cqfd' runs command set in .cqfdrc
################################################################################
jtest_prepare "cqfd run command set in .cqfdrc"
if "$cqfd" && grep -qw "cqfd" "$test_file"; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

################################################################################
# 'cqfd' runs command overriden by the command line
################################################################################
jtest_prepare "cqfd run command overriden by the command-line"
if "$cqfd" touch "$test_file" && test -e "$test_file" && ! test -s "$test_file"; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f "$test_file"

################################################################################
# If the Dockerfile changed and no init is done again, 'cqfd' should fail
################################################################################
jtest_prepare "Modifying the Dockerfile should require running 'cqfd init' again"
dockerfile=.cqfd/docker/Dockerfile
echo "RUN echo $RANDOM" >>"$dockerfile"
if ! "$cqfd"; then
	jtest_result pass
else
	jtest_result fail
fi
# restore Dockerfile
sed -i '$d' "$dockerfile"
