#!/usr/bin/env bash
#
# validate the behavior of run with working directory

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

workdir="workingdir"
mkdir -p "$workdir"

# move .cqfd and .cqfdrc
mv .cqfd "$workdir/.cqfd"
mv .cqfdrc "$workdir/.cqfdrc"

cd "$workdir" || exit 1

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

sed -e "/\[build\]/,/^$/s,^command=.*$,command='stat --printf '%u:' . ..'," .cqfdrc.orig >.cqfdrc

jtest_prepare "run cqfd without --working-directory should own working directory and should not own its parent directory"
if cqfd | grep "^$UID:0:$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with --working-directory set to inexistent directory should fail"
if ! cqfd -w "nonexistentdir"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with --working-directory set to parent directory should own parent directory and should not own its parent directory"
if cqfd -w ".." | grep "^$UID:0:$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with --working-directory set to parent directory using absolute path should own parent directory and should not own its parent directory"
if cqfd -w "$PWD/.." | grep "^$UID:0:$"; then
	jtest_result pass
else
	jtest_result fail

fi

jtest_prepare "run cqfd with CQFD_WORKDIR set to inexistent directory should fail"
if ! CQFD_WORKDIR="nonexistentdir" cqfd; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with CQFD_WORKDIR set to parent directory should own parent directory and should not own its parent directory"
if CQFD_WORKDIR=".." cqfd | grep "^$UID:0:$"; then
	jtest_result pass
else
	jtest_result fail

fi

jtest_prepare "run cqfd with CQFD_WORKDIR set to parent directory using absolute path should own parent directory and should not own its parent directory"
if CQFD_WORKDIR="$PWD/.." cqfd | grep "^$UID:0:$"; then
	jtest_result pass
else
	jtest_result fail

fi

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc

cd "$OLDPWD" || exit 1

# moveback .cqfdrc and .cqfd
mv "$workdir/.cqfdrc" .cqfdrc
mv "$workdir/.cqfd" .cqfd

# cleanup
rmdir -p "$workdir"
