#!/usr/bin/env bash
#
# validate the behavior of release command

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd release without files parameter should fail"
if ! cqfd release; then
	jtest_result pass
else
	jtest_result fail
fi

files=(a/cqfd_a.txt a/b/c/cqfd_c.txt a/b/cqfd_b.txt)
cp -f .cqfdrc .cqfdrc.orig
echo "files=\"${files[*]}\"" >>.cqfdrc
jtest_prepare "run cqfd release with a files parameter should pass"
if cqfd release; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd release should generate orgname-project.tar.xz tarball archive by default"
if tar tf cqfd-test.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd release should preserve pathnames in tarball archive"
result="pass"
for f in "${files[@]}"; do
	if ! tar tf cqfd-test.tar.xz | grep "^$f$"; then
		result="fail"
	fi
done
jtest_result "$result"
unset result
# cleanup
make clean
rm -f cqfd-test.tar.xz

jtest_prepare "run cqfd release with tar_transform=no should preserve pathnames in tarball archive"
echo "tar_transform=no" >>.cqfdrc
if cqfd release; then
	result="pass"
else
	result="fail"
fi
for f in "${files[@]}"; do
	if ! tar tf cqfd-test.tar.xz | grep "^$f$"; then
		result="fail"
	fi
done
jtest_result "$result"
unset result
# revert the changes in .cqfdrc file
sed -i -e '$ s!^tar_transform=.*$!!' .cqfdrc
# cleanup
make clean
rm -f cqfd-test.tar.xz

jtest_prepare "run cqfd release with tar_transform=yes should not preserve pathnames in tarball archive"
echo "tar_transform=yes" >>.cqfdrc
if cqfd release; then
	result="pass"
else
	result="fail"
fi
for f in "${files[@]}"; do
	if ! tar tf cqfd-test.tar.xz | grep "^${f##*/}$"; then
		result="fail"
	fi
done
jtest_result "$result"
unset result
# revert the changes in .cqfdrc file
sed -i -e '$ s!^tar_transform=.*$!!' .cqfdrc
# cleanup
make clean
rm -f cqfd-test.tar.xz

jtest_prepare "run cqfd release with tar_options=-h should follows symlinks in tarball archive"
result="pass"
if ! cqfd run ln -s a/cqfd_a.txt link.txt; then
	jtest_log fatal "cqfd run failed"
	result="fail"
fi
sed -i '/files=/d' .cqfdrc
echo "files=\"a/cqfd_a.txt link.txt\"" >>.cqfdrc
echo "tar_options=-h" >>.cqfdrc

if ! cqfd release; then
	jtest_log fatal "cqfd release failed"
	result="fail"
fi
mkdir "$TDIR/output"
if ! tar xf cqfd-test.tar.xz -C "$TDIR/output"; then
	jtest_log fatal "tar failed"
	result="fail"
fi
if [ -L "$TDIR/output/link.txt" ] || ! diff "$TDIR/output/a/cqfd_a.txt" "$TDIR/output/link.txt"; then
	jtest_log fatal "link.txt is not a symlink or differs from cqfd_a.txt"
	result="fail"
fi
jtest_result "$result"
unset result

# revert the changes in .cqfdrc file
sed -i '/tar_options=/d' .cqfdrc
sed -i '/files=/d' .cqfdrc
echo "files=\"${files[*]}\"" >>.cqfdrc

# cleanup
make clean
rm -f link.txt cqfd-test.tar.xz
rm -Rf "$TDIR/output"

jtest_prepare "run cqfd release with archive=cqfd-%D3-\$CTEST.tar.xz should template tarball archive filename (RFC3339 date)"
export CTEST=foobar
d3="$(date --rfc-3339='date')"
# shellcheck disable=SC2016
echo 'archive=cqfd-%D3-$CTEST.tar.xz' >>.cqfdrc
if cqfd release && tar tf "cqfd-$d3-foobar.tar.xz" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "cqfd-$d3-foobar.tar.xz"

jtest_prepare "run cqfd release with archive=cqfd-%Gh-\$CTEST.tar.xz should template tarball archive filename (git short hash of last commit)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*$!archive=cqfd-%Gh-$CTEST.tar.xz!' .cqfdrc
# shellcheck disable=SC2010
if cqfd release &&
   ls -1 cqfd-*-foobar.tar.xz | grep -E "^cqfd-([[:xdigit:]]{4,40}|unset)-foobar.tar.xz$" &&
   tar tf cqfd-*-foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-*-foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%GH-\$CTEST.tar.xz should template tarball archive filename (git long hash of last commit)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*$!archive=cqfd-%GH-$CTEST.tar.xz!' .cqfdrc
# shellcheck disable=SC2010
if cqfd release &&
   ls -1 cqfd-*-foobar.tar.xz | grep -E "^cqfd-([[:xdigit:]]{40}|unset)-foobar.tar.xz$" &&
   tar tf cqfd-*-foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-*-foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%Du-\$CTEST.tar.xz should template tarball archive filename (Unix timestamp)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*$!archive=cqfd-%Du-$CTEST.tar.xz!' .cqfdrc
# shellcheck disable=SC2010
if cqfd release &&
   ls -1 cqfd-*-foobar.tar.xz | grep -E "^cqfd-[[:digit:]]{1,20}-foobar.tar.xz$" &&
   tar tf cqfd-*-foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-*-foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%Cf-\$CTEST.tar.xz should template tarball archive filename (current cqfd flavor name unset)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*$!archive=cqfd-%Cf-$CTEST.tar.xz!' .cqfdrc
if cqfd release && tar tf cqfd--foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd--foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%Cf-\$CTEST.tar.xz should template tarball archive filename (current cqfd flavor name set)"
if cqfd -b foo release && tar tf cqfd-foo.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-foo.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%Po-\$CTEST.tar.xz should template tarball archive filename (value of the project.org configuration key)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*$!archive=cqfd-%Po-$CTEST.tar.xz!' .cqfdrc
if cqfd release && tar tf cqfd-cqfd-foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-cqfd-foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%Pn-\$CTEST.tar.xz should template tarball archive filename (value of the project.name configuration key)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*$!archive=cqfd-%Pn-$CTEST.tar.xz!' .cqfdrc
if cqfd release && tar tf cqfd-test-foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-test-foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-%%-\$CTEST.tar.xz should template tarball archive filename (litteral '%' sign)"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*!archive=cqfd-%%-$CTEST.tar.xz!' .cqfdrc
if cqfd release && tar tf cqfd-%-foobar.tar.xz &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-%-foobar.tar.xz

jtest_prepare "run cqfd release with archive=cqfd-\$CTEST.tar.gz should generate a gzipped tarball archive"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*xz$!archive=cqfd-$CTEST.tar.gz!' .cqfdrc
if cqfd release && tar ztf "cqfd-$CTEST.tar.gz" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "cqfd-$CTEST.tar.gz"

jtest_prepare "run cqfd release with archive=cqfd-\$CTEST.zip should generate a zip archive"
# shellcheck disable=SC2016
sed -i -e '$ s!^archive=.*gz$!archive=cqfd-$CTEST.zip!' .cqfdrc
if cqfd release && unzip -l "cqfd-$CTEST.zip" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "cqfd-$CTEST.zip"

for flav in foo bar; do
	jtest_prepare "run cqfd release with flavor '$flav' and archive=cqfd-%Cf.tar.xz should template tarball archive filename (current cqfd flavor name set)"

	if cqfd -b "$flav" release && \
	   tar tf "cqfd-$flav.tar.xz" &>/dev/null; then
		jtest_result pass
	else
		jtest_result fail
	fi
	# cleanup
	rm -f "cqfd-$flav.tar.xz"
done

jtest_prepare "run cqfd release with a non-existing file or directory in files parameter should fail"
sed -i -e 's!^files=.*$!files="ThisFileDoesNotExist.txt"!' .cqfdrc
if ! cqfd release; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd release should resolve globbing pathnames in files parameter"
# shellcheck disable=SC2016
sed -i -e 's!^archive=.*$!archive=cqfd-$CTEST.tar.xz!' .cqfdrc
sed -i -e 's!^files=.*$!files=".cq*rc Ma*"!' .cqfdrc
# cqfd release must work without error
if cqfd release; then
	jtest_result pass
else
	jtest_result fail
fi

# the generated archive should contain our expanded globs
jtest_prepare "run cqfd release should archive globbing pathnames in archive"
tar tf "cqfd-$CTEST.tar.xz" >"tmp.$$"
if ! grep -q '^.cqfdrc$' "tmp.$$" ||
   ! grep -q '^Makefile$' "tmp.$$"; then
	jtest_result fail
else
	jtest_result pass
fi
# cleanup
rm -f "cqfd-$CTEST.tar.xz"
rm -f "tmp.$$"

jtest_prepare "run cqfd release with unsupported archive format in archive parameter should fail"
# shellcheck disable=SC2016
sed -i -e 's!^archive=.*$!archive=cqfd-$CTEST.tar.zst!' .cqfdrc
if ! cqfd release; then
	jtest_result pass
else
	jtest_result fail
fi

# shellcheck disable=SC2016
sed -i -e 's!^archive=.*$!archive=cqfd-$CTEST.tar.xz!' .cqfdrc
sed -i -e 's!^files=.*$!files=".local/bin/cqfd"!' .cqfdrc
jtest_prepare "run cqfd with option --release should pass"
if cqfd --release; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with option --release should generate orgname-\$CTEST.tar.xz tarball archive by default"
if tar tf "cqfd-$CTEST.tar.xz" &>/dev/null; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f "cqfd-$CTEST.tar.xz"

# cleanup
make clean

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
