#!/usr/bin/env bash
#
# validate the behavior of exec command

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig

jtest_prepare "run cqfd exec without argument should fail"
if ! cqfd exec; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd exec with arguments should pass"
if cqfd exec true; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd exec should return same status"
if cqfd exec exit 10; \
   test "$?" -eq 10; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd exec should preserve the arguments"
# shellcheck disable=SC2016
if cqfd exec /bin/sh -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "^0=zero,\*=one two three,#=3$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd exec with option --release should generate cqfd-test.tar.xz tarball archive by default"
echo "files=\"exec\"" >>.cqfdrc
if cqfd --release exec touch exec && tar tf cqfd-test.tar.xz | grep "^exec$"; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-test.tar.xz exec

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
