#!/usr/bin/env bash
#
# validate the behavior of shell command

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f Cqfdfile Cqfdfile.orig

jtest_prepare "run cqfd shell without stdin should pass"
if cqfd shell </dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd shell should read commands from stdin"
if ( ! cqfd shell <<<"tty" ) | grep "^not a tty$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd shell should use program set in shell"
sed '/\[build\]/ashell="/bin/bash"' Cqfdfile.orig >Cqfdfile
# shellcheck disable=SC2016
if cqfd bash <<<'printf "$0"' | grep "^bash$"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore Cqfdfile
mv -f Cqfdfile.orig Cqfdfile

jtest_prepare "run cqfd shell should preserve the arguments"
# shellcheck disable=SC2016
if cqfd shell -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "^0=zero,\*=one two three,#=3$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd shell should run shell script"
if cqfd shell ./whereami.sh 2>&1 | grep "^Ubuntu .* LTS$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd bash should run shell script"
if cqfd bash ./whereami.sh 2>&1 | grep "^Ubuntu .* LTS$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd shell as a shell interpreter should pass"
if PATH="$TDIR/.local/bin:$PATH"; ./whereami.sh 2>&1 | grep "^Ubuntu .* LTS$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd shell as a SHELL= program should pass"
if ! command -v make 2>/dev/null; then
	jtest_result skip
else
	if PATH="$TDIR/.local/bin:$PATH"; make whereami 2>&1 | grep "^Ubuntu .* LTS$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

cp -f Cqfdfile Cqfdfile.orig
echo "files=\"shell\"" >>Cqfdfile
jtest_prepare "run cqfd shell with option --release should generate cqfd-test.tar.xz tarball archive"
if cqfd --release shell -c "touch shell" && tar tf cqfd-test.tar.xz | grep "^shell$"; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-test.tar.xz shell

# restore initial Cqfdfile
mv -f Cqfdfile.orig Cqfdfile
