#!/usr/bin/env bash
#
# validate the behavior of shell command

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.local/bin/cqfd"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig

jtest_prepare "cqfd shell should succeed with no stdin"
if "$cqfd" shell </dev/null; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should read commands from stdin"
if ( ! "$cqfd" shell <<<"tty" ) | grep "not a tty"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell should use interpreter set in shell"
sed '/\[build\]/ashell="/bin/bash"' .cqfdrc.orig >.cqfdrc
# shellcheck disable=SC2016
if "$cqfd" bash <<<'printf "$0"' | grep -q "^bash$"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore .cqfdrc
mv -f .cqfdrc.orig .cqfdrc

jtest_prepare "cqfd shell should preserve the arguments"
# shellcheck disable=SC2016
if "$cqfd" shell -c 'printf "0=$0,*=$*,#=$#"' zero one two three \
       | grep "0=zero,\*=one two three,#=3$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd sh should succeed and use sh"
# shellcheck disable=SC2016
if "$cqfd" sh <<<'printf "$0"' | grep -q "^sh$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd bash should succeed and use bash"
# shellcheck disable=SC2016
if "$cqfd" bash <<<'printf "$0"' | grep -q "^bash$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd dash should succeed and use dash"
# shellcheck disable=SC2016
if "$cqfd" dash <<<'printf "$0"' | grep -q "^dash$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell is usable to run shell script"
if "$cqfd" shell ./whereami.sh 2>&1 | grep "^Ubuntu .* LTS$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd bash is usable to run shell script"
if "$cqfd" bash ./whereami.sh 2>&1 | grep "^Ubuntu .* LTS$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell is usable as a shell interpreter script"
if PATH="$TDIR/.local/bin:$PATH"; ./whereami.sh 2>&1 | grep "^Ubuntu .* LTS$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd shell is usable as a shell interpreter in binaries"
if ! command -v make 2>/dev/null; then
	jtest_result skip
else
	if PATH="$TDIR/.local/bin:$PATH"; make whereami 2>&1 | grep "^Ubuntu .* LTS$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

cp -f .cqfdrc .cqfdrc.orig
echo "files=\"shell\"" >>.cqfdrc
jtest_prepare "cqfd shell should release"
if "$cqfd" --release shell -c "touch shell" && tar tf cqfd-test.tar.xz | grep -q "^shell$"; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm -f cqfd-test.tar.xz shell

# restore initial .cqfdrc
mv -f .cqfdrc.orig .cqfdrc
