#!/usr/bin/env bash
#
# validate the allocation of pty and the behavior of redirections

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup .cqfdrc
mv .cqfdrc .cqfdrc.orig

sed -e "/\[build\]/,/^$/s/^command=.*$/command='tty || true'/" .cqfdrc.orig >.cqfdrc

jtest_prepare "run cqfd with stdin and stdout attached to tty should allocate a pty"
if ! tty; then
	jtest_result skip
else
	if cqfd; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd with stdin attached to tty and stdout piped should not allocate a pty"
if ! tty; then
	jtest_result skip
else
	if cqfd | grep "^not a tty$"; then
		jtest_result pass
	else
		jtest_result fail
	fi
fi

jtest_prepare "run cqfd with stdin redirected to /dev/null should not allocate a pty"
if cqfd </dev/null | grep "^not a tty$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with stdout piped should not allocate a pty"
if cqfd | grep "^not a tty$"; then
	jtest_result pass
else
	jtest_result fail
fi

sed -e "/\[build\]/,/^$/s,^command=.*$,command='echo stdout \&\& echo stderr >\&2'," -i .cqfdrc

jtest_prepare "run cqfd with allocated pty should redirect stdout and stderr to same endpoint"
if cqfd >out; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm out

jtest_prepare "run cqfd without allocated pty should redirect stdout and stderr to distinct endpoints"
if cqfd >out 2>err && grep '^stdout$' out && grep '^stderr$' err; then
	jtest_result pass
else
	jtest_result fail
fi
# cleanup
rm out err

# restore .cqfdrc
mv .cqfdrc.orig .cqfdrc
