#!/usr/bin/env bash
#
# validate the behavior of running docker in cqfd using host docker daemon

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.cqfd/cqfd"
cqfd_docker="${CQFD_DOCKER:-docker}"

cd "$TDIR/" || exit 1

jtest_prepare "cqfd run docker using host docker daemon"
if [ "$cqfd_docker" != "docker" ] || ! getent group docker | grep -q "$USER"; then
	jtest_result skip
else
	cp -f .cqfdrc .cqfdrc.old
	cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.old
	cp -f .cqfd/docker/Dockerfile.doutofd .cqfd/docker/Dockerfile
	sed -i -e "/\[build\]/,/^$/s,^command=.*$,command='docker run --rm -ti ubuntu:24.04 cat /etc/os-release'," .cqfdrc

	if "$cqfd" init && CQFD_BIND_DOCKER_SOCK=true "$cqfd" | grep -qE 'PRETTY_NAME="Ubuntu 24.04(.[[:digit:]]+)? LTS"'; then
		jtest_result pass
	else
		jtest_result fail
	fi
	# restore .cqfdrc and Dockerfile
	mv -f .cqfdrc.old .cqfdrc
	mv -f .cqfd/docker/Dockerfile.old .cqfd/docker/Dockerfile
fi
