#!/usr/bin/env bash
#
# validate the behavior of running docker multi-platform image

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

cp -f Cqfdfile Cqfdfile.orig
cp -f Cqfdfile-multi_platform Cqfdfile
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.multi_platform .cqfd/docker/Dockerfile

native_machine=x86_64
cross_machine=aarch64
native_platform=linux/amd64
cross_platform=linux/arm64
if uname -m | grep -q "^aarch64$"; then
	native_machine=aarch64
	cross_machine=x86_64
	native_platform=linux/arm64
	cross_platform=linux/amd64
fi

jtest_prepare "run cqfd without environment CQFD_PLATFORM and option --platform should run native docker platform ($native_platform = $native_machine)"
if cqfd init && cqfd | grep "^$native_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with environment CQFD_PLATFORM should run native docker platform ($native_platform = $native_machine)"
if CQFD_PLATFORM="$native_platform" cqfd init && \
   CQFD_PLATFORM="$native_platform" cqfd | grep "^$native_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with option --platform should run native docker platform ($native_platform = $native_machine)"
if cqfd --platform "$native_platform" init && \
   cqfd --platform "$native_platform" | grep "^$native_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with environment CQFD_PLATFORM should run cross docker platform ($cross_platform = $cross_machine)"
if CQFD_PLATFORM="$cross_platform" cqfd init && \
   CQFD_PLATFORM="$cross_platform" cqfd | grep "^$cross_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd with option --platform should run cross docker platform ($cross_platform = $cross_machine)"
if cqfd --platform "$cross_platform" init && \
   cqfd --platform "$cross_platform" | grep "^$cross_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd docker platform helpers should run associated docker platform (linux/amd64, linux/aarch64)"
if linux-amd64-cqfd | grep "^x86_64$" && \
   linux-arm64-cqfd | grep "^aarch64$"; then
	jtest_result pass
else
	jtest_result fail
fi

# restore Cqfdfile and Dockerfile
mv -f Cqfdfile.orig Cqfdfile
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
