#!/usr/bin/env bash
#
# validate the behavior of running docker multi-platform image

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"
cqfd="$TDIR/.local/bin/cqfd"

cd "$TDIR/" || exit 1

cp -f .cqfdrc .cqfdrc.orig
cp -f cqfdrc-multi_platform .cqfdrc
cp -f .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp -f .cqfd/docker/Dockerfile.multi_platform .cqfd/docker/Dockerfile

native_machine=x86_64
cross_machine=aarch64
native_platform=linux/amd64
cross_platform=linux/arm64
if uname -m | grep -q "^aarch64$"; then
	native_machine=aarch64
	cross_machine=x86_64
	native_platform=linux/arm64
	cross_platform=linux/amd64
fi

jtest_prepare "cqfd run native docker platform without environment CQFD_PLATFORM or option --platform ($native_platform = $native_machine)"
if "$cqfd" init && "$cqfd" | grep "^$native_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd run native docker platform with environment CQFD_PLATFORM ($native_platform = $native_machine)"
if CQFD_PLATFORM="$native_platform" "$cqfd" init && \
   CQFD_PLATFORM="$native_platform" "$cqfd" | grep "^$native_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd run native docker platform with option --platform ($native_platform = $native_machine)"
if "$cqfd" --platform "$native_platform" init && \
   "$cqfd" --platform "$native_platform" | grep "^$native_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd run cross docker platform with environment CQFD_PLATFORM ($cross_platform = $cross_machine)"
if CQFD_PLATFORM="$cross_platform" "$cqfd" init && \
   CQFD_PLATFORM="$cross_platform" "$cqfd" | grep "^$cross_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "cqfd run cross docker platform with option --platform ($cross_platform = $cross_machine)"
if "$cqfd" --platform "$cross_platform" init && \
   "$cqfd" --platform "$cross_platform" | grep "^$cross_machine$"; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "Test cross platform helper scripts (linux/amd64, linux/aarch64)"
ln -sf "$cqfd" linux-amd64-cqfd
ln -sf "$cqfd" linux-arm64-cqfd
if bash linux-amd64-cqfd | grep "^x86_64$" && \
   bash linux-arm64-cqfd | grep "^aarch64$"; then
	jtest_result pass
else
	jtest_result fail
fi
rm -f linux-amd64-cqfd
rm -f linux-arm64-cqfd

# restore .cqfdrc and Dockerfile
mv -f .cqfdrc.orig .cqfdrc
mv -f .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! "$cqfd" init; then
	jtest_log error "restore container failed"
fi
