#!/usr/bin/env bash
#
# validate the behavior of running docker multi-platform image

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

# backup Dockefile and .cqfdrc
cp .cqfd/docker/Dockerfile .cqfd/docker/Dockerfile.orig
cp .cqfdrc .cqfdrc.orig

cp .cqfd/docker/Dockerfile.platform .cqfd/docker/Dockerfile
cp cqfdrc-platform .cqfdrc

jtest_prepare "run cqfd with FROM --platform=linux/arm64 in Dockerfile should run linux/arm64 docker platform"
if cqfd init && cqfd | grep "^aarch64$"; then
	jtest_result pass
else
	jtest_result fail
fi
# restore .cqfdrc and Dockerfile
mv .cqfdrc.orig .cqfdrc
mv .cqfd/docker/Dockerfile.orig .cqfd/docker/Dockerfile

# restore container
if ! cqfd init; then
	jtest_log error "restore container failed"
fi
