#!/usr/bin/env bash
#
# validate the behavior of deinit command

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

jtest_prepare "run cqfd deinit with a proper .cqfdrc should pass"
if cqfd deinit; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd deinit with a nonexisting Dockerfile should fail"
cp -f .cqfdrc .cqfdrc.orig
sed -i -e "s/\[build\]/[build]\ndistro='thisshouldfail'/" .cqfdrc
if ! cqfd deinit; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd deinit with another Dockerfile should pass"
sed -i -e "s/thisshouldfail/centos/" .cqfdrc
if cqfd init && cqfd deinit; then
	jtest_result pass
else
	jtest_result fail
fi
# restore cqfdrc
mv -f .cqfdrc.orig .cqfdrc

jtest_prepare "run cqfd deinit with an already deinit'ed image should fail"
if ! cqfd deinit; then
	jtest_result pass
else
	jtest_result fail
fi

jtest_prepare "run cqfd deinit with CQFD_EXTRA_RMI_ARGS=--force should pass"
if CQFD_EXTRA_RMI_ARGS="--force" cqfd deinit; then
	jtest_result pass
else
	jtest_result fail
fi
