#!/usr/bin/env bash
#
# validate the behavior of ls and gc command to teardown

set -o pipefail

. "$(dirname "$0")/jtest.inc" "$1"

cd "$TDIR/" || exit 1

################################################################################
# Ensure all build containers are "Outdated"
################################################################################
for i in .cqfd/*/Dockerfile; do
	test -e "$i" || continue
	echo "RUN echo $EPOCHSECONDS" >>"$i"
done

################################################################################
# 'cqfd ls' should list build containers
################################################################################
jtest_prepare "run cqfd ls should list build containers"
if cqfd ls | grep -E "^cqfd-$USER-.+$";
   test "${PIPESTATUS[0]}" -eq 0 -a "${PIPESTATUS[1]}" -eq 0; then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd gc' should collects the build containers
################################################################################
jtest_prepare "run cqfd gc should collect unused build containers"
if CQFD_PROMPT=yes cqfd gc && ( ! cqfd ls | grep -E "^cqfd-$USER-.+[[:blank:]]+(Deleted|Outdated)[[:blank:]][[:alnum:]/.-]+$" && \
	           test "${PIPESTATUS[0]}" -eq 0 -a "${PIPESTATUS[1]}" -eq 1 ); then
	jtest_result pass
else
	jtest_result fail
fi

################################################################################
# 'cqfd ls' should not list the build containers
################################################################################
jtest_prepare "run cqfd should not list build containers"
if ! cqfd ls | grep -E "^cqfd-$USER-.+$" && \
   test "${PIPESTATUS[0]}" -eq 0 -a "${PIPESTATUS[1]}" -eq 1; then
	jtest_result pass
else
	jtest_result fail
fi
