#!/bin/sh
# See deb-prerm(5).

set -e

DEB_HOST_MULTIARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"

case "$1" in
remove)
  rm -f "/usr/lib/$DEB_HOST_MULTIARCH/docker/cli-plugins/docker-cqfd"
  ;;
esac

update-alternatives \
  --remove Cqfdfile.5.gz /usr/share/man/man5/Cqfdfile6.5.gz
update-alternatives \
  --remove cqfd.1.gz /usr/share/man/man1/cqfd6.1.gz
update-alternatives \
  --remove cqfd /usr/bin/cqfd6

#DEBHELPER#
